export interface Player {
  name: string
  team: string
  position: string
}

export const PLAYERS: Player[] = [
  // Argentina
  { name: 'Juan Musso', team: 'Argentina', position: 'GOL' },
  { name: 'Gerónimo Rulli', team: 'Argentina', position: 'GOL' },
  { name: 'Emiliano Martínez', team: 'Argentina', position: 'GOL' },
  { name: 'Leonardo Balerdi', team: 'Argentina', position: 'DEF' },
  { name: 'Nicolás Tagliafico', team: 'Argentina', position: 'DEF' },
  { name: 'Gonzalo Montiel', team: 'Argentina', position: 'DEF' },
  { name: 'Lisandro Martínez', team: 'Argentina', position: 'DEF' },
  { name: 'Cristian Romero', team: 'Argentina', position: 'DEF' },
  { name: 'Nicolás Otamendi', team: 'Argentina', position: 'DEF' },
  { name: 'Facundo Medina', team: 'Argentina', position: 'DEF' },
  { name: 'Nahuel Molina', team: 'Argentina', position: 'DEF' },
  { name: 'Valentín Barco', team: 'Argentina', position: 'DEF' },
  { name: 'Leandro Paredes', team: 'Argentina', position: 'MEI' },
  { name: 'Rodrigo de Paul', team: 'Argentina', position: 'MEI' },
  { name: 'Giovani Lo Celso', team: 'Argentina', position: 'MEI' },
  { name: 'Exequiel Palacios', team: 'Argentina', position: 'MEI' },
  { name: 'Nicolás González', team: 'Argentina', position: 'MEI' },
  { name: 'Alexis Mac Allister', team: 'Argentina', position: 'MEI' },
  { name: 'Enzo Fernández', team: 'Argentina', position: 'MEI' },
  { name: 'Lionel Messi', team: 'Argentina', position: 'MEI' },
  { name: 'Thiago Almada', team: 'Argentina', position: 'MEI' },
  { name: 'Julián Álvarez', team: 'Argentina', position: 'ATA' },
  { name: 'Giuliano Simeone', team: 'Argentina', position: 'ATA' },
  { name: 'Nicolás Paz', team: 'Argentina', position: 'ATA' },
  { name: 'José López', team: 'Argentina', position: 'ATA' },
  { name: 'Lautaro Martínez', team: 'Argentina', position: 'ATA' },

  // Australia
  { name: 'Mathew Ryan', team: 'Australia', position: 'GOL' },
  { name: 'Paul Izzo', team: 'Australia', position: 'GOL' },
  { name: 'Patrick Beach', team: 'Australia', position: 'GOL' },
  { name: 'Miloš Degenek', team: 'Australia', position: 'DEF' },
  { name: 'Alessandro Circati', team: 'Australia', position: 'DEF' },
  { name: 'Jacob Italiano', team: 'Australia', position: 'DEF' },
  { name: 'Jordan Bos', team: 'Australia', position: 'DEF' },
  { name: 'Jason Geria', team: 'Australia', position: 'DEF' },
  { name: 'Kai Trewin', team: 'Australia', position: 'DEF' },
  { name: 'Aziz Behich', team: 'Australia', position: 'DEF' },
  { name: 'Harry Souttar', team: 'Australia', position: 'DEF' },
  { name: 'Cameron Burgess', team: 'Australia', position: 'DEF' },
  { name: 'Lucas Herrington', team: 'Australia', position: 'DEF' },
  { name: 'Connor Metcalfe', team: 'Australia', position: 'MEI' },
  { name: 'Aiden O\'Neill', team: 'Australia', position: 'MEI' },
  { name: 'Cameron Devlin', team: 'Australia', position: 'MEI' },
  { name: 'Jackson Irvine', team: 'Australia', position: 'MEI' },
  { name: 'Paul Okon-Engstler', team: 'Australia', position: 'MEI' },
  { name: 'Mathew Leckie', team: 'Australia', position: 'ATA' },
  { name: 'Mohamed Touré', team: 'Australia', position: 'ATA' },
  { name: 'Ajdin Hrustić', team: 'Australia', position: 'ATA' },
  { name: 'Awer Mabil', team: 'Australia', position: 'ATA' },
  { name: 'Nestory Irankunda', team: 'Australia', position: 'ATA' },
  { name: 'Cristian Volpato', team: 'Australia', position: 'ATA' },
  { name: 'Nishan Velupillay', team: 'Australia', position: 'ATA' },
  { name: 'Tete Yengi', team: 'Australia', position: 'ATA' },

  // Algeria
  { name: 'Melvin Mastil', team: 'Algeria', position: 'GOL' },
  { name: 'Oussama Benbot', team: 'Algeria', position: 'GOL' },
  { name: 'Luca Zidane', team: 'Algeria', position: 'GOL' },
  { name: 'Aïssa Mandi', team: 'Algeria', position: 'DEF' },
  { name: 'Achraf Abada', team: 'Algeria', position: 'DEF' },
  { name: 'Mohamed Tougaï', team: 'Algeria', position: 'DEF' },
  { name: 'Zineddine Belaïd', team: 'Algeria', position: 'DEF' },
  { name: 'Jaouen Hadjam', team: 'Algeria', position: 'DEF' },
  { name: 'Rayan Aït-Nouri', team: 'Algeria', position: 'DEF' },
  { name: 'Rafik Belghali', team: 'Algeria', position: 'DEF' },
  { name: 'Ramy Bensebaini', team: 'Algeria', position: 'DEF' },
  { name: 'Samir Chergui', team: 'Algeria', position: 'DEF' },
  { name: 'Ramiz Zerrouki', team: 'Algeria', position: 'MEI' },
  { name: 'Houssem Aouar', team: 'Algeria', position: 'MEI' },
  { name: 'Fares Chaïbi', team: 'Algeria', position: 'MEI' },
  { name: 'Hicham Boudaoui', team: 'Algeria', position: 'MEI' },
  { name: 'Nabil Bentaleb', team: 'Algeria', position: 'MEI' },
  { name: 'Ibrahim Maza', team: 'Algeria', position: 'MEI' },
  { name: 'Yassine Titraoui', team: 'Algeria', position: 'MEI' },
  { name: 'Riyad Mahrez', team: 'Algeria', position: 'ATA' },
  { name: 'Amine Gouiri', team: 'Algeria', position: 'ATA' },
  { name: 'Anis Hadj Moussa', team: 'Algeria', position: 'ATA' },
  { name: 'Nadhir Benbouali', team: 'Algeria', position: 'ATA' },
  { name: 'Mohamed Amoura', team: 'Algeria', position: 'ATA' },
  { name: 'Adil Boulbina', team: 'Algeria', position: 'ATA' },
  { name: 'Fares Ghedjemis', team: 'Algeria', position: 'ATA' },

  // Austria
  { name: 'Alexander Schlager', team: 'Austria', position: 'GOL' },
  { name: 'Florian Wiegele', team: 'Austria', position: 'GOL' },
  { name: 'Patrick Pentz', team: 'Austria', position: 'GOL' },
  { name: 'David Affengruber', team: 'Austria', position: 'DEF' },
  { name: 'Kevin Danso', team: 'Austria', position: 'DEF' },
  { name: 'Stefan Posch', team: 'Austria', position: 'DEF' },
  { name: 'David Alaba', team: 'Austria', position: 'DEF' },
  { name: 'Philipp Lienhart', team: 'Austria', position: 'DEF' },
  { name: 'Phillip Mwene', team: 'Austria', position: 'DEF' },
  { name: 'Marco Friedl', team: 'Austria', position: 'DEF' },
  { name: 'Michael Svoboda', team: 'Austria', position: 'DEF' },
  { name: 'Xaver Schlager', team: 'Austria', position: 'MEI' },
  { name: 'Nicolas Seiwald', team: 'Austria', position: 'MEI' },
  { name: 'Marcel Sabitzer', team: 'Austria', position: 'MEI' },
  { name: 'Florian Grillitsch', team: 'Austria', position: 'MEI' },
  { name: 'Carney Chukwuemeka', team: 'Austria', position: 'MEI' },
  { name: 'Romano Schmid', team: 'Austria', position: 'MEI' },
  { name: 'Christoph Baumgartner', team: 'Austria', position: 'MEI' },
  { name: 'Konrad Laimer', team: 'Austria', position: 'MEI' },
  { name: 'Alexander Prass', team: 'Austria', position: 'MEI' },
  { name: 'Paul Wanner', team: 'Austria', position: 'MEI' },
  { name: 'Alessandro Schöpf', team: 'Austria', position: 'ATA' },
  { name: 'Marko Arnautović', team: 'Austria', position: 'ATA' },
  { name: 'Michael Gregoritsch', team: 'Austria', position: 'ATA' },
  { name: 'Saša Kalajdžić', team: 'Austria', position: 'ATA' },
  { name: 'Patrick Wimmer', team: 'Austria', position: 'ATA' },

  // Belgium
  { name: 'Thibaut Courtois', team: 'Belgium', position: 'GOL' },
  { name: 'Senne Lammens', team: 'Belgium', position: 'GOL' },
  { name: 'Mike Penders', team: 'Belgium', position: 'GOL' },
  { name: 'Zeno Debast', team: 'Belgium', position: 'DEF' },
  { name: 'Arthur Theate', team: 'Belgium', position: 'DEF' },
  { name: 'Brandon Mechele', team: 'Belgium', position: 'DEF' },
  { name: 'Maxim De Cuyper', team: 'Belgium', position: 'DEF' },
  { name: 'Thomas Meunier', team: 'Belgium', position: 'DEF' },
  { name: 'Koni De Winter', team: 'Belgium', position: 'DEF' },
  { name: 'Joaquin Seys', team: 'Belgium', position: 'DEF' },
  { name: 'Timothy Castagne', team: 'Belgium', position: 'DEF' },
  { name: 'Nathan Ngoy', team: 'Belgium', position: 'DEF' },
  { name: 'Axel Witsel', team: 'Belgium', position: 'MEI' },
  { name: 'Kevin De Bruyne', team: 'Belgium', position: 'MEI' },
  { name: 'Youri Tielemans', team: 'Belgium', position: 'MEI' },
  { name: 'Diego Moreira', team: 'Belgium', position: 'MEI' },
  { name: 'Hans Vanaken', team: 'Belgium', position: 'MEI' },
  { name: 'Alexis Saelemaekers', team: 'Belgium', position: 'MEI' },
  { name: 'Nicolas Raskin', team: 'Belgium', position: 'MEI' },
  { name: 'Amadou Onana', team: 'Belgium', position: 'MEI' },
  { name: 'Romelu Lukaku', team: 'Belgium', position: 'ATA' },
  { name: 'Leandro Trossard', team: 'Belgium', position: 'ATA' },
  { name: 'Jérémy Doku', team: 'Belgium', position: 'ATA' },
  { name: 'Dodi Lukebakio', team: 'Belgium', position: 'ATA' },
  { name: 'Charles De Ketelaere', team: 'Belgium', position: 'ATA' },
  { name: 'Matías Fernández-Pardo', team: 'Belgium', position: 'ATA' },

  // DR Congo
  { name: 'Lionel Mpasi', team: 'DR Congo', position: 'GOL' },
  { name: 'Timothy Fayulu', team: 'DR Congo', position: 'GOL' },
  { name: 'Matthieu Epolo', team: 'DR Congo', position: 'GOL' },
  { name: 'Aaron Wan-Bissaka', team: 'DR Congo', position: 'DEF' },
  { name: 'Steve Kapuadi', team: 'DR Congo', position: 'DEF' },
  { name: 'Axel Tuanzebe', team: 'DR Congo', position: 'DEF' },
  { name: 'Dylan Batubinsika', team: 'DR Congo', position: 'DEF' },
  { name: 'Joris Kayembe', team: 'DR Congo', position: 'DEF' },
  { name: 'Chancel Mbemba', team: 'DR Congo', position: 'DEF' },
  { name: 'Gédéon Kalulu', team: 'DR Congo', position: 'DEF' },
  { name: 'Arthur Masuaku', team: 'DR Congo', position: 'DEF' },
  { name: 'Ngalayel Mukau', team: 'DR Congo', position: 'MEI' },
  { name: 'Nathanaël Mbuku', team: 'DR Congo', position: 'MEI' },
  { name: 'Samuel Moutoussamy', team: 'DR Congo', position: 'MEI' },
  { name: 'Théo Bongonda', team: 'DR Congo', position: 'MEI' },
  { name: 'Noah Sadiki', team: 'DR Congo', position: 'MEI' },
  { name: 'Aaron Tshibola', team: 'DR Congo', position: 'MEI' },
  { name: 'Charles Pickel', team: 'DR Congo', position: 'MEI' },
  { name: 'Edo Kayembe', team: 'DR Congo', position: 'MEI' },
  { name: 'Brian Cipenga', team: 'DR Congo', position: 'MEI' },
  { name: 'Gaël Kakuta', team: 'DR Congo', position: 'ATA' },
  { name: 'Meschack Elia', team: 'DR Congo', position: 'ATA' },
  { name: 'Cédric Bakambu', team: 'DR Congo', position: 'ATA' },
  { name: 'Fiston Mayele', team: 'DR Congo', position: 'ATA' },
  { name: 'Yoane Wissa', team: 'DR Congo', position: 'ATA' },
  { name: 'Simon Banza', team: 'DR Congo', position: 'ATA' },

  // Cape Verde
  { name: 'Vozinha', team: 'Cape Verde', position: 'GOL' },
  { name: 'Márcio Rosa', team: 'Cape Verde', position: 'GOL' },
  { name: 'CJ Dos Santos', team: 'Cape Verde', position: 'GOL' },
  { name: 'Stopira', team: 'Cape Verde', position: 'DEF' },
  { name: 'Diney Borges', team: 'Cape Verde', position: 'DEF' },
  { name: 'Pico Lopes', team: 'Cape Verde', position: 'DEF' },
  { name: 'Logan Costa', team: 'Cape Verde', position: 'DEF' },
  { name: 'Sidny Cabral', team: 'Cape Verde', position: 'DEF' },
  { name: 'Steven Moreira', team: 'Cape Verde', position: 'DEF' },
  { name: 'Wagner Pina', team: 'Cape Verde', position: 'DEF' },
  { name: 'Kelvin Pires', team: 'Cape Verde', position: 'MEI' },
  { name: 'Kevin Pina', team: 'Cape Verde', position: 'MEI' },
  { name: 'Jovane Cabral', team: 'Cape Verde', position: 'MEI' },
  { name: 'João Paulo', team: 'Cape Verde', position: 'MEI' },
  { name: 'Jamiro Monteiro', team: 'Cape Verde', position: 'MEI' },
  { name: 'Garry Rodrigues', team: 'Cape Verde', position: 'MEI' },
  { name: 'Deroy Duarte', team: 'Cape Verde', position: 'MEI' },
  { name: 'Laros Duarte', team: 'Cape Verde', position: 'MEI' },
  { name: 'Yannick Semedo', team: 'Cape Verde', position: 'MEI' },
  { name: 'Willy Semedo', team: 'Cape Verde', position: 'ATA' },
  { name: 'Telmo Arcanjo', team: 'Cape Verde', position: 'ATA' },
  { name: 'Nuno da Costa', team: 'Cape Verde', position: 'ATA' },
  { name: 'Hélio Varela', team: 'Cape Verde', position: 'ATA' },
  { name: 'Gilson Benchimol', team: 'Cape Verde', position: 'ATA' },
  { name: 'Dailon Livramento', team: 'Cape Verde', position: 'ATA' },
  { name: 'Ryan Mendes', team: 'Cape Verde', position: 'ATA' },

  // Bosnia & Herzegovina
  { name: 'Nikola Vasilj', team: 'Bosnia & Herzegovina', position: 'GOL' },
  { name: 'Mladen Jurkas', team: 'Bosnia & Herzegovina', position: 'GOL' },
  { name: 'Martin Zlomislić', team: 'Bosnia & Herzegovina', position: 'GOL' },
  { name: 'Nihad Mujakić', team: 'Bosnia & Herzegovina', position: 'DEF' },
  { name: 'Dennis Hadžikadunic', team: 'Bosnia & Herzegovina', position: 'DEF' },
  { name: 'Tarik Muharemović', team: 'Bosnia & Herzegovina', position: 'DEF' },
  { name: 'Sead Kolašinac', team: 'Bosnia & Herzegovina', position: 'DEF' },
  { name: 'Amar Dedić', team: 'Bosnia & Herzegovina', position: 'DEF' },
  { name: 'Nikola Katić', team: 'Bosnia & Herzegovina', position: 'DEF' },
  { name: 'Stjepan Radeljić', team: 'Bosnia & Herzegovina', position: 'DEF' },
  { name: 'Nidal Čelik', team: 'Bosnia & Herzegovina', position: 'DEF' },
  { name: 'Benjamin Tahirović', team: 'Bosnia & Herzegovina', position: 'MEI' },
  { name: 'Armin Gigović', team: 'Bosnia & Herzegovina', position: 'MEI' },
  { name: 'Ivan Bašić', team: 'Bosnia & Herzegovina', position: 'MEI' },
  { name: 'Ivan Šunjić', team: 'Bosnia & Herzegovina', position: 'MEI' },
  { name: 'Amar Memić', team: 'Bosnia & Herzegovina', position: 'MEI' },
  { name: 'Amir Hadžiahmetović', team: 'Bosnia & Herzegovina', position: 'MEI' },
  { name: 'Dženis Burnić', team: 'Bosnia & Herzegovina', position: 'MEI' },
  { name: 'Ermin Mahmić', team: 'Bosnia & Herzegovina', position: 'MEI' },
  { name: 'Samed Bazdar', team: 'Bosnia & Herzegovina', position: 'MEI' },
  { name: 'Ermedin Demirović', team: 'Bosnia & Herzegovina', position: 'ATA' },
  { name: 'Edin Džeko', team: 'Bosnia & Herzegovina', position: 'ATA' },
  { name: 'Kerim Alajbegović', team: 'Bosnia & Herzegovina', position: 'ATA' },
  { name: 'Esmir Bajraktarević', team: 'Bosnia & Herzegovina', position: 'ATA' },
  { name: 'Haris Tabaković', team: 'Bosnia & Herzegovina', position: 'ATA' },
  { name: 'Jovo Lukić', team: 'Bosnia & Herzegovina', position: 'ATA' },

  // Brazil
  { name: 'Alisson Becker', team: 'Brazil', position: 'GOL' },
  { name: 'Weverton Caldeira', team: 'Brazil', position: 'GOL' },
  { name: 'Ederson Moraes', team: 'Brazil', position: 'GOL' },
  { name: 'Wesley', team: 'Brazil', position: 'DEF' },
  { name: 'Gabriel Magalhães', team: 'Brazil', position: 'DEF' },
  { name: 'Marcos Corrêa', team: 'Brazil', position: 'DEF' },
  { name: 'Alex Sandro', team: 'Brazil', position: 'DEF' },
  { name: 'Danilo Luiz', team: 'Brazil', position: 'DEF' },
  { name: 'Bremer', team: 'Brazil', position: 'DEF' },
  { name: 'Léo Pereira', team: 'Brazil', position: 'DEF' },
  { name: 'Douglas Santos', team: 'Brazil', position: 'DEF' },
  { name: 'Roger Ibanez', team: 'Brazil', position: 'DEF' },
  { name: 'Carlos Casimiro', team: 'Brazil', position: 'MEI' },
  { name: 'Bruno Guimarães', team: 'Brazil', position: 'MEI' },
  { name: 'Fábio Tavares', team: 'Brazil', position: 'MEI' },
  { name: 'Danilo Santos', team: 'Brazil', position: 'MEI' },
  { name: 'Lucas Paquetá', team: 'Brazil', position: 'MEI' },
  { name: 'Vinícius Júnior', team: 'Brazil', position: 'ATA' },
  { name: 'Matheus Cunha', team: 'Brazil', position: 'ATA' },
  { name: 'Neymar Santos', team: 'Brazil', position: 'ATA' },
  { name: 'Raphael Belloli', team: 'Brazil', position: 'ATA' },
  { name: 'Endrick Sousa', team: 'Brazil', position: 'ATA' },
  { name: 'Luiz Henrique', team: 'Brazil', position: 'ATA' },
  { name: 'Gabriel Martinelli', team: 'Brazil', position: 'ATA' },
  { name: 'Igor Thiago', team: 'Brazil', position: 'ATA' },
  { name: 'Rayan', team: 'Brazil', position: 'ATA' },

  // England
  { name: 'Jordan Pickford', team: 'England', position: 'GOL' },
  { name: 'Dean Henderson', team: 'England', position: 'GOL' },
  { name: 'James Trafford', team: 'England', position: 'GOL' },
  { name: 'Ezri Konsa', team: 'England', position: 'DEF' },
  { name: 'Nico O\'Reilly', team: 'England', position: 'DEF' },
  { name: 'John Stones', team: 'England', position: 'DEF' },
  { name: 'Marc Guéhi', team: 'England', position: 'DEF' },
  { name: 'Valentino Livramento', team: 'England', position: 'DEF' },
  { name: 'Daniel Burn', team: 'England', position: 'DEF' },
  { name: 'Reece James', team: 'England', position: 'DEF' },
  { name: 'Djed Spence', team: 'England', position: 'DEF' },
  { name: 'Jarell Quansah', team: 'England', position: 'DEF' },
  { name: 'Declan Rice', team: 'England', position: 'MEI' },
  { name: 'Elliot Anderson', team: 'England', position: 'MEI' },
  { name: 'Jude Bellingham', team: 'England', position: 'MEI' },
  { name: 'Jordan Henderson', team: 'England', position: 'MEI' },
  { name: 'Kobbie Mainoo', team: 'England', position: 'MEI' },
  { name: 'Morgan Rogers', team: 'England', position: 'MEI' },
  { name: 'Eberechi Eze', team: 'England', position: 'MEI' },
  { name: 'Bukayo Saka', team: 'England', position: 'ATA' },
  { name: 'Harry Kane', team: 'England', position: 'ATA' },
  { name: 'Marcus Rashford', team: 'England', position: 'ATA' },
  { name: 'Anthony Gordon', team: 'England', position: 'ATA' },
  { name: 'Oliver Watkins', team: 'England', position: 'ATA' },
  { name: 'Noni Madueke', team: 'England', position: 'ATA' },
  { name: 'Ivan Toney', team: 'England', position: 'ATA' },

  // France
  { name: 'Brice Samba', team: 'France', position: 'GOL' },
  { name: 'Mike Maignan', team: 'France', position: 'GOL' },
  { name: 'Robin Risser', team: 'France', position: 'GOL' },
  { name: 'Malo Gusto', team: 'France', position: 'DEF' },
  { name: 'Lucas Digne', team: 'France', position: 'DEF' },
  { name: 'Dayot Upamecano', team: 'France', position: 'DEF' },
  { name: 'Jules Koundé', team: 'France', position: 'DEF' },
  { name: 'Ibrahima Konaté', team: 'France', position: 'DEF' },
  { name: 'William Saliba', team: 'France', position: 'DEF' },
  { name: 'Théo Hernandez', team: 'France', position: 'DEF' },
  { name: 'Lucas Hernandez', team: 'France', position: 'DEF' },
  { name: 'Maxence Lacroix', team: 'France', position: 'DEF' },
  { name: 'Manu Koné', team: 'France', position: 'MEI' },
  { name: 'Aurélien Tchouaméni', team: 'France', position: 'MEI' },
  { name: 'N\'Golo Kanté', team: 'France', position: 'MEI' },
  { name: 'Adrien Rabiot', team: 'France', position: 'MEI' },
  { name: 'Warren Zaïre-Emery', team: 'France', position: 'MEI' },
  { name: 'Rayan Cherki', team: 'France', position: 'MEI' },
  { name: 'Maghnes Akliouche', team: 'France', position: 'MEI' },
  { name: 'Ousmane Dembélé', team: 'France', position: 'ATA' },
  { name: 'Marcus Thuram', team: 'France', position: 'ATA' },
  { name: 'Kylian Mbappé', team: 'France', position: 'ATA' },
  { name: 'Michaël Olise', team: 'France', position: 'ATA' },
  { name: 'Bradley Barcola', team: 'France', position: 'ATA' },
  { name: 'Désiré Doué', team: 'France', position: 'ATA' },
  { name: 'Jean-Philippe Mateta', team: 'France', position: 'ATA' },

  // Ghana
  { name: 'Lawrence Zigi', team: 'Ghana', position: 'GOL' },
  { name: 'Joseph Anang', team: 'Ghana', position: 'GOL' },
  { name: 'Benjamin Asare', team: 'Ghana', position: 'GOL' },
  { name: 'Alidu Seidu', team: 'Ghana', position: 'DEF' },
  { name: 'Jonas Adjetey', team: 'Ghana', position: 'DEF' },
  { name: 'Abdul Mumin', team: 'Ghana', position: 'DEF' },
  { name: 'Gideon Mensah', team: 'Ghana', position: 'DEF' },
  { name: 'Baba Rahman', team: 'Ghana', position: 'DEF' },
  { name: 'Jerome Opoku', team: 'Ghana', position: 'DEF' },
  { name: 'Kojo Oppong', team: 'Ghana', position: 'DEF' },
  { name: 'Derrick Luckassen', team: 'Ghana', position: 'DEF' },
  { name: 'Marvin Senaya', team: 'Ghana', position: 'DEF' },
  { name: 'Caleb Yirenkyi', team: 'Ghana', position: 'MEI' },
  { name: 'Thomas Partey', team: 'Ghana', position: 'MEI' },
  { name: 'Kwasi Sibo', team: 'Ghana', position: 'MEI' },
  { name: 'Antoine Semenyo', team: 'Ghana', position: 'MEI' },
  { name: 'Elisha Owusu', team: 'Ghana', position: 'MEI' },
  { name: 'Augustine Boakye', team: 'Ghana', position: 'MEI' },
  { name: 'Fatawu Issahaku', team: 'Ghana', position: 'ATA' },
  { name: 'Jordan Ayew', team: 'Ghana', position: 'ATA' },
  { name: 'Brandon Thomas-Asante', team: 'Ghana', position: 'ATA' },
  { name: 'Christopher Baah', team: 'Ghana', position: 'ATA' },
  { name: 'Iñaki Williams', team: 'Ghana', position: 'ATA' },
  { name: 'Kamaldeen Sulemana', team: 'Ghana', position: 'ATA' },
  { name: 'Ernest Nuamah', team: 'Ghana', position: 'ATA' },
  { name: 'Prince Adu', team: 'Ghana', position: 'ATA' },

  // Germany
  { name: 'Manuel Neuer', team: 'Germany', position: 'GOL' },
  { name: 'Oliver Baumann', team: 'Germany', position: 'GOL' },
  { name: 'Alexander Nübel', team: 'Germany', position: 'GOL' },
  { name: 'Antonio Rüdiger', team: 'Germany', position: 'DEF' },
  { name: 'Waldemar Anton', team: 'Germany', position: 'DEF' },
  { name: 'Jonathan Tah', team: 'Germany', position: 'DEF' },
  { name: 'Joshua Kimmich', team: 'Germany', position: 'DEF' },
  { name: 'Nico Schlotterbeck', team: 'Germany', position: 'DEF' },
  { name: 'Nathaniel Brown', team: 'Germany', position: 'DEF' },
  { name: 'David Raum', team: 'Germany', position: 'DEF' },
  { name: 'Malick Thiaw', team: 'Germany', position: 'DEF' },
  { name: 'Aleksandar Pavlović', team: 'Germany', position: 'MEI' },
  { name: 'Leon Goretzka', team: 'Germany', position: 'MEI' },
  { name: 'Jamie Leweling', team: 'Germany', position: 'MEI' },
  { name: 'Jamal Musiala', team: 'Germany', position: 'MEI' },
  { name: 'Pascal Groß', team: 'Germany', position: 'MEI' },
  { name: 'Angelo Stiller', team: 'Germany', position: 'MEI' },
  { name: 'Florian Wirtz', team: 'Germany', position: 'MEI' },
  { name: 'Leroy Sané', team: 'Germany', position: 'MEI' },
  { name: 'Nadiem Amiri', team: 'Germany', position: 'MEI' },
  { name: 'Felix Nmecha', team: 'Germany', position: 'MEI' },
  { name: 'Lennart Karl', team: 'Germany', position: 'ATA' },
  { name: 'Kai Havertz', team: 'Germany', position: 'ATA' },
  { name: 'Nick Woltemade', team: 'Germany', position: 'ATA' },
  { name: 'Maximilian Beier', team: 'Germany', position: 'ATA' },
  { name: 'Deniz Undav', team: 'Germany', position: 'ATA' },

  // Canada
  { name: 'Dayne St. Clair', team: 'Canada', position: 'GOL' },
  { name: 'Maxime Crépeau', team: 'Canada', position: 'GOL' },
  { name: 'Owen Goodman', team: 'Canada', position: 'GOL' },
  { name: 'Alistair Johnston', team: 'Canada', position: 'DEF' },
  { name: 'Alfie Jones', team: 'Canada', position: 'DEF' },
  { name: 'Luc de Fougerolles', team: 'Canada', position: 'DEF' },
  { name: 'Joel Waterman', team: 'Canada', position: 'DEF' },
  { name: 'Derek Cornelius', team: 'Canada', position: 'DEF' },
  { name: 'Moïse Bombito', team: 'Canada', position: 'DEF' },
  { name: 'Alphonso Davies', team: 'Canada', position: 'DEF' },
  { name: 'Richie Laryea', team: 'Canada', position: 'DEF' },
  { name: 'Niko Sigur', team: 'Canada', position: 'DEF' },
  { name: 'Mathieu Choinière', team: 'Canada', position: 'MEI' },
  { name: 'Stephen Eustaquio', team: 'Canada', position: 'MEI' },
  { name: 'Ismaël Koné', team: 'Canada', position: 'MEI' },
  { name: 'Liam Millar', team: 'Canada', position: 'MEI' },
  { name: 'Jacob Shaffelburg', team: 'Canada', position: 'MEI' },
  { name: 'Jonathan Osorio', team: 'Canada', position: 'MEI' },
  { name: 'Nathan Saliba', team: 'Canada', position: 'MEI' },
  { name: 'Marcelo Flores', team: 'Canada', position: 'MEI' },
  { name: 'Cyle Larin', team: 'Canada', position: 'ATA' },
  { name: 'Jonathan David', team: 'Canada', position: 'ATA' },
  { name: 'Tani Oluwaseyi', team: 'Canada', position: 'ATA' },
  { name: 'Tajon Buchanan', team: 'Canada', position: 'ATA' },
  { name: 'Ali Ahmed', team: 'Canada', position: 'ATA' },
  { name: 'Promise David', team: 'Canada', position: 'ATA' },

  // Colombia
  { name: 'David Ospina', team: 'Colombia', position: 'GOL' },
  { name: 'Camilo Vargas', team: 'Colombia', position: 'GOL' },
  { name: 'Álvaro Montero', team: 'Colombia', position: 'GOL' },
  { name: 'Daniel Muñoz', team: 'Colombia', position: 'DEF' },
  { name: 'Jhon Lucumí', team: 'Colombia', position: 'DEF' },
  { name: 'Santiago Arias', team: 'Colombia', position: 'DEF' },
  { name: 'Yerry Mina', team: 'Colombia', position: 'DEF' },
  { name: 'Gustavo Puerta', team: 'Colombia', position: 'DEF' },
  { name: 'Johan Mojica', team: 'Colombia', position: 'DEF' },
  { name: 'Willer Ditta', team: 'Colombia', position: 'DEF' },
  { name: 'Deiver Machado', team: 'Colombia', position: 'DEF' },
  { name: 'Dávinson Sánchez', team: 'Colombia', position: 'DEF' },
  { name: 'Kevin Castaño', team: 'Colombia', position: 'MEI' },
  { name: 'Richard Ríos', team: 'Colombia', position: 'MEI' },
  { name: 'Jorge Carrascal', team: 'Colombia', position: 'MEI' },
  { name: 'James Rodríguez', team: 'Colombia', position: 'MEI' },
  { name: 'Jhon Arias', team: 'Colombia', position: 'MEI' },
  { name: 'Juan Portilla', team: 'Colombia', position: 'MEI' },
  { name: 'Jefferson Lerma', team: 'Colombia', position: 'MEI' },
  { name: 'Juan Quintero', team: 'Colombia', position: 'MEI' },
  { name: 'Luis Díaz', team: 'Colombia', position: 'ATA' },
  { name: 'Jhon Córdoba', team: 'Colombia', position: 'ATA' },
  { name: 'Juan Hernández', team: 'Colombia', position: 'ATA' },
  { name: 'Leandro Campaz', team: 'Colombia', position: 'ATA' },
  { name: 'Luis Suárez', team: 'Colombia', position: 'ATA' },
  { name: 'Andrés Gómez', team: 'Colombia', position: 'ATA' },

  // Curaçao
  { name: 'Eloy Room', team: 'Curaçao', position: 'GOL' },
  { name: 'Tyrick Bodak', team: 'Curaçao', position: 'GOL' },
  { name: 'Trevor Doornbusch', team: 'Curaçao', position: 'GOL' },
  { name: 'Shurandy Sambo', team: 'Curaçao', position: 'DEF' },
  { name: 'Jurien Gaari', team: 'Curaçao', position: 'DEF' },
  { name: 'Roshon van Eijma', team: 'Curaçao', position: 'DEF' },
  { name: 'Sherel Floranus', team: 'Curaçao', position: 'DEF' },
  { name: 'Armando Obispo', team: 'Curaçao', position: 'DEF' },
  { name: 'Joshua Brenet', team: 'Curaçao', position: 'DEF' },
  { name: 'Riechedly Bazoer', team: 'Curaçao', position: 'MEI' },
  { name: 'Deveron Fonville', team: 'Curaçao', position: 'MEI' },
  { name: 'Godfried Roemeratoe', team: 'Curaçao', position: 'MEI' },
  { name: 'Juninho Bacuna', team: 'Curaçao', position: 'MEI' },
  { name: 'Livano Comenencia', team: 'Curaçao', position: 'MEI' },
  { name: 'Leandro Bacuna', team: 'Curaçao', position: 'MEI' },
  { name: 'Arjany Martha', team: 'Curaçao', position: 'MEI' },
  { name: 'Tahith Chong', team: 'Curaçao', position: 'MEI' },
  { name: 'Kevin Felida', team: 'Curaçao', position: 'MEI' },
  { name: 'Jürgen Locadia', team: 'Curaçao', position: 'ATA' },
  { name: 'Jeremy Antonisse', team: 'Curaçao', position: 'ATA' },
  { name: 'Sontje Hansen', team: 'Curaçao', position: 'ATA' },
  { name: 'Tyrese Noslin', team: 'Curaçao', position: 'ATA' },
  { name: 'Kenji Gorre', team: 'Curaçao', position: 'ATA' },
  { name: 'Jearl Margaritha', team: 'Curaçao', position: 'ATA' },
  { name: 'Brandley Kuwas', team: 'Curaçao', position: 'ATA' },
  { name: 'Gervane Kastaneer', team: 'Curaçao', position: 'ATA' },

  // Croatia
  { name: 'Dominik Livaković', team: 'Croatia', position: 'GOL' },
  { name: 'Ivor Pandur', team: 'Croatia', position: 'GOL' },
  { name: 'Dominik Kotarski', team: 'Croatia', position: 'GOL' },
  { name: 'Josip Stanišić', team: 'Croatia', position: 'DEF' },
  { name: 'Marin Pongračić', team: 'Croatia', position: 'DEF' },
  { name: 'Joško Gvardiol', team: 'Croatia', position: 'DEF' },
  { name: 'Duje Čaleta-Car', team: 'Croatia', position: 'DEF' },
  { name: 'Josip Šutalo', team: 'Croatia', position: 'DEF' },
  { name: 'Kristijan Jakić', team: 'Croatia', position: 'DEF' },
  { name: 'Luka Vušković', team: 'Croatia', position: 'DEF' },
  { name: 'Martin Erlić', team: 'Croatia', position: 'DEF' },
  { name: 'Nikola Moro', team: 'Croatia', position: 'MEI' },
  { name: 'Mateo Kovačić', team: 'Croatia', position: 'MEI' },
  { name: 'Luka Modrić', team: 'Croatia', position: 'MEI' },
  { name: 'Nikola Vlašić', team: 'Croatia', position: 'MEI' },
  { name: 'Mario Pašalić', team: 'Croatia', position: 'MEI' },
  { name: 'Martin Baturina', team: 'Croatia', position: 'MEI' },
  { name: 'Petar Sučić', team: 'Croatia', position: 'MEI' },
  { name: 'Toni Fruk', team: 'Croatia', position: 'MEI' },
  { name: 'Luka Sučić', team: 'Croatia', position: 'MEI' },
  { name: 'Andrej Kramarić', team: 'Croatia', position: 'ATA' },
  { name: 'Ante Budimir', team: 'Croatia', position: 'ATA' },
  { name: 'Ivan Perišić', team: 'Croatia', position: 'ATA' },
  { name: 'Igor Matanović', team: 'Croatia', position: 'ATA' },
  { name: 'Marco Pašalić', team: 'Croatia', position: 'ATA' },
  { name: 'Petar Musa', team: 'Croatia', position: 'ATA' },

  // Czechia
  { name: 'Matěj Kovář', team: 'Czechia', position: 'GOL' },
  { name: 'Jindřich Stánek', team: 'Czechia', position: 'GOL' },
  { name: 'Lukáš Horníček', team: 'Czechia', position: 'GOL' },
  { name: 'David Zima', team: 'Czechia', position: 'DEF' },
  { name: 'Tomáš Holeš', team: 'Czechia', position: 'DEF' },
  { name: 'Robin Hranáč', team: 'Czechia', position: 'DEF' },
  { name: 'Vladimír Coufal', team: 'Czechia', position: 'DEF' },
  { name: 'Štěpán Chaloupek', team: 'Czechia', position: 'DEF' },
  { name: 'Ladislav Krejčí', team: 'Czechia', position: 'DEF' },
  { name: 'David Jurásek', team: 'Czechia', position: 'DEF' },
  { name: 'Jaroslav Zelený', team: 'Czechia', position: 'DEF' },
  { name: 'David Doudera', team: 'Czechia', position: 'DEF' },
  { name: 'Vladimír Darida', team: 'Czechia', position: 'MEI' },
  { name: 'Lukáš Červ', team: 'Czechia', position: 'MEI' },
  { name: 'Lukáš Provod', team: 'Czechia', position: 'MEI' },
  { name: 'Michal Sadílek', team: 'Czechia', position: 'MEI' },
  { name: 'Tomáš Souček', team: 'Czechia', position: 'MEI' },
  { name: 'Alexandr Sojka', team: 'Czechia', position: 'MEI' },
  { name: 'Hugo Šochůrek', team: 'Czechia', position: 'MEI' },
  { name: 'Adam Hložek', team: 'Czechia', position: 'ATA' },
  { name: 'Patrik Schick', team: 'Czechia', position: 'ATA' },
  { name: 'Jan Kuchta', team: 'Czechia', position: 'ATA' },
  { name: 'Mojmír Chytil', team: 'Czechia', position: 'ATA' },
  { name: 'Pavel Šulc', team: 'Czechia', position: 'ATA' },
  { name: 'Tomáš Chorý', team: 'Czechia', position: 'ATA' },
  { name: 'Denis Višinský', team: 'Czechia', position: 'ATA' },

  // Egypt
  { name: 'Mohamed Elshenawy', team: 'Egypt', position: 'GOL' },
  { name: 'Mahdy Soliman', team: 'Egypt', position: 'GOL' },
  { name: 'Mostafa Shoubir', team: 'Egypt', position: 'GOL' },
  { name: 'Mohamed Alaa', team: 'Egypt', position: 'DEF' },
  { name: 'Yasser Ibrahim', team: 'Egypt', position: 'DEF' },
  { name: 'Mohamed Hany', team: 'Egypt', position: 'DEF' },
  { name: 'Hossam Abdelmaguid', team: 'Egypt', position: 'DEF' },
  { name: 'Ramy Rabia', team: 'Egypt', position: 'DEF' },
  { name: 'Mohamed Abdelmoneim', team: 'Egypt', position: 'DEF' },
  { name: 'Ahmed Fatouh', team: 'Egypt', position: 'DEF' },
  { name: 'Karim Hafez', team: 'Egypt', position: 'DEF' },
  { name: 'Tarek Alaa', team: 'Egypt', position: 'DEF' },
  { name: 'Emam Ashour', team: 'Egypt', position: 'MEI' },
  { name: 'Mostafa Zico', team: 'Egypt', position: 'MEI' },
  { name: 'Hamdy Fathy', team: 'Egypt', position: 'MEI' },
  { name: 'Mohanad Lashin', team: 'Egypt', position: 'MEI' },
  { name: 'Nabil Donga', team: 'Egypt', position: 'MEI' },
  { name: 'Marawan Attia', team: 'Egypt', position: 'MEI' },
  { name: 'Mahmoud Saber', team: 'Egypt', position: 'MEI' },
  { name: 'Mahmoud Hassan', team: 'Egypt', position: 'MEI' },
  { name: 'Hamza Abdelkarim', team: 'Egypt', position: 'MEI' },
  { name: 'Mohamed Salah', team: 'Egypt', position: 'ATA' },
  { name: 'Haissem Hassan', team: 'Egypt', position: 'ATA' },
  { name: 'Ibrahim Adel', team: 'Egypt', position: 'ATA' },
  { name: 'Omar Marmoush', team: 'Egypt', position: 'ATA' },
  { name: 'Mahmoud Hamdy', team: 'Egypt', position: 'ATA' },

  // Ecuador
  { name: 'Hernán Galíndez', team: 'Ecuador', position: 'GOL' },
  { name: 'Moisés Ramírez', team: 'Ecuador', position: 'GOL' },
  { name: 'Gonzalo Valle', team: 'Ecuador', position: 'GOL' },
  { name: 'Félix Torres', team: 'Ecuador', position: 'DEF' },
  { name: 'Piero Hincapié', team: 'Ecuador', position: 'DEF' },
  { name: 'Joel Ordóñez', team: 'Ecuador', position: 'DEF' },
  { name: 'Willian Pacho', team: 'Ecuador', position: 'DEF' },
  { name: 'Pervis Estupiñán', team: 'Ecuador', position: 'DEF' },
  { name: 'Ángelo Preciado', team: 'Ecuador', position: 'DEF' },
  { name: 'Jackson Porozo', team: 'Ecuador', position: 'DEF' },
  { name: 'Yaimar Medina', team: 'Ecuador', position: 'DEF' },
  { name: 'Jordy Alcívar', team: 'Ecuador', position: 'MEI' },
  { name: 'Anthony Valencia', team: 'Ecuador', position: 'MEI' },
  { name: 'Kendry Páez', team: 'Ecuador', position: 'MEI' },
  { name: 'Alan Minda', team: 'Ecuador', position: 'MEI' },
  { name: 'Pedro Vite', team: 'Ecuador', position: 'MEI' },
  { name: 'Denil Castillo', team: 'Ecuador', position: 'MEI' },
  { name: 'Alan Franco', team: 'Ecuador', position: 'MEI' },
  { name: 'Moisés Caicedo', team: 'Ecuador', position: 'MEI' },
  { name: 'John Yeboah', team: 'Ecuador', position: 'ATA' },
  { name: 'Kevin Rodríguez', team: 'Ecuador', position: 'ATA' },
  { name: 'Enner Valencia', team: 'Ecuador', position: 'ATA' },
  { name: 'Jordy Caicedo', team: 'Ecuador', position: 'ATA' },
  { name: 'Gonzalo Plata', team: 'Ecuador', position: 'ATA' },
  { name: 'Nilson Angulo', team: 'Ecuador', position: 'ATA' },
  { name: 'Jeremy Arévalo', team: 'Ecuador', position: 'ATA' },

  // Haiti
  { name: 'Johny Placide', team: 'Haiti', position: 'GOL' },
  { name: 'Alexandre Pierre', team: 'Haiti', position: 'GOL' },
  { name: 'Josué Duverger', team: 'Haiti', position: 'GOL' },
  { name: 'Carlens Arcus', team: 'Haiti', position: 'DEF' },
  { name: 'Keeto Thermoncy', team: 'Haiti', position: 'DEF' },
  { name: 'Ricardo Ade', team: 'Haiti', position: 'DEF' },
  { name: 'Hannes Delcroix', team: 'Haiti', position: 'DEF' },
  { name: 'Martin Expérience', team: 'Haiti', position: 'DEF' },
  { name: 'Markhus Lacroix', team: 'Haiti', position: 'DEF' },
  { name: 'Jean-Kevin Duverne', team: 'Haiti', position: 'DEF' },
  { name: 'Wilguens Paugain', team: 'Haiti', position: 'DEF' },
  { name: 'Carl Sainte', team: 'Haiti', position: 'MEI' },
  { name: 'Jean-Ricner Bellegarde', team: 'Haiti', position: 'MEI' },
  { name: 'Leverton Pierre', team: 'Haiti', position: 'MEI' },
  { name: 'Danley Jean Jacques', team: 'Haiti', position: 'MEI' },
  { name: 'Dominique Simon', team: 'Haiti', position: 'MEI' },
  { name: 'Woodensky Pierre', team: 'Haiti', position: 'MEI' },
  { name: 'Derrick Etienne', team: 'Haiti', position: 'MEI' },
  { name: 'Duckens Nazon', team: 'Haiti', position: 'ATA' },
  { name: 'Louicius Deedson', team: 'Haiti', position: 'ATA' },
  { name: 'Ruben Providence', team: 'Haiti', position: 'ATA' },
  { name: 'Lenny Joseph', team: 'Haiti', position: 'ATA' },
  { name: 'Wilson Isidor', team: 'Haiti', position: 'ATA' },
  { name: 'Yassin Fortune', team: 'Haiti', position: 'ATA' },
  { name: 'Frantzdy Pierrot', team: 'Haiti', position: 'ATA' },

  // Iraq
  { name: 'Fahad Talib', team: 'Iraq', position: 'GOL' },
  { name: 'Jalal Hassan', team: 'Iraq', position: 'GOL' },
  { name: 'Ahmed Basil', team: 'Iraq', position: 'GOL' },
  { name: 'Rebin Ghareeb', team: 'Iraq', position: 'DEF' },
  { name: 'Hussein Ali', team: 'Iraq', position: 'DEF' },
  { name: 'Zaid Tahseen', team: 'Iraq', position: 'DEF' },
  { name: 'Akam Hashim', team: 'Iraq', position: 'DEF' },
  { name: 'Munaf Younus', team: 'Iraq', position: 'DEF' },
  { name: 'Ahmed Yahya', team: 'Iraq', position: 'DEF' },
  { name: 'Merchas Doski', team: 'Iraq', position: 'DEF' },
  { name: 'Mustafa Saadoon', team: 'Iraq', position: 'DEF' },
  { name: 'Frans Putros', team: 'Iraq', position: 'MEI' },
  { name: 'Youssef Amyn', team: 'Iraq', position: 'MEI' },
  { name: 'Ibrahim Bayesh', team: 'Iraq', position: 'MEI' },
  { name: 'Zidane Iqbal', team: 'Iraq', position: 'MEI' },
  { name: 'Amir Al-Ammari', team: 'Iraq', position: 'MEI' },
  { name: 'Kevin Yakob', team: 'Iraq', position: 'MEI' },
  { name: 'Aimar Sher', team: 'Iraq', position: 'MEI' },
  { name: 'Zaid Ismael', team: 'Iraq', position: 'MEI' },
  { name: 'Ali Al-Hamadi', team: 'Iraq', position: 'ATA' },
  { name: 'Mohanad Ali', team: 'Iraq', position: 'ATA' },
  { name: 'Ahmed Qasim', team: 'Iraq', position: 'ATA' },
  { name: 'Ali Yousif', team: 'Iraq', position: 'ATA' },
  { name: 'Ali Jasim', team: 'Iraq', position: 'ATA' },
  { name: 'Aymen Hussein', team: 'Iraq', position: 'ATA' },
  { name: 'Marko Farji', team: 'Iraq', position: 'ATA' },

  // Ivory Coast
  { name: 'Yahia Fofana', team: 'Ivory Coast', position: 'GOL' },
  { name: 'Mohamed Koné', team: 'Ivory Coast', position: 'GOL' },
  { name: 'Alban Lafont', team: 'Ivory Coast', position: 'GOL' },
  { name: 'Ousmane Diomandé', team: 'Ivory Coast', position: 'DEF' },
  { name: 'Ghislain Konan', team: 'Ivory Coast', position: 'DEF' },
  { name: 'Wilfried Singo', team: 'Ivory Coast', position: 'DEF' },
  { name: 'Odilon Kossounou', team: 'Ivory Coast', position: 'DEF' },
  { name: 'Christopher Operi', team: 'Ivory Coast', position: 'DEF' },
  { name: 'Guela Doué', team: 'Ivory Coast', position: 'DEF' },
  { name: 'Emmanuel Agbadou', team: 'Ivory Coast', position: 'DEF' },
  { name: 'Evan Ndicka', team: 'Ivory Coast', position: 'DEF' },
  { name: 'Jean Séri', team: 'Ivory Coast', position: 'MEI' },
  { name: 'Seko Fofana', team: 'Ivory Coast', position: 'MEI' },
  { name: 'Franck Kessié', team: 'Ivory Coast', position: 'MEI' },
  { name: 'Ibrahim Sangaré', team: 'Ivory Coast', position: 'MEI' },
  { name: 'Parfait Guiagon', team: 'Ivory Coast', position: 'MEI' },
  { name: 'Christ Oulai', team: 'Ivory Coast', position: 'MEI' },
  { name: 'Ange-Yoan Bonny', team: 'Ivory Coast', position: 'MEI' },
  { name: 'Simon Adingra', team: 'Ivory Coast', position: 'ATA' },
  { name: 'Yan Diomandé', team: 'Ivory Coast', position: 'ATA' },
  { name: 'Elye Wahi', team: 'Ivory Coast', position: 'ATA' },
  { name: 'Oumar Diakité', team: 'Ivory Coast', position: 'ATA' },
  { name: 'Amad Diallo', team: 'Ivory Coast', position: 'ATA' },
  { name: 'Nicolas Pépé', team: 'Ivory Coast', position: 'ATA' },
  { name: 'Evann Guessand', team: 'Ivory Coast', position: 'ATA' },
  { name: 'Bazoumana Touré', team: 'Ivory Coast', position: 'ATA' },

  // Japan
  { name: 'Zion Suzuki', team: 'Japan', position: 'GOL' },
  { name: 'Keisuke Osako', team: 'Japan', position: 'GOL' },
  { name: 'Tomoki Hayakawa', team: 'Japan', position: 'GOL' },
  { name: 'Yukinari Sugawara', team: 'Japan', position: 'DEF' },
  { name: 'Shogo Taniguchi', team: 'Japan', position: 'DEF' },
  { name: 'Kou Itakura', team: 'Japan', position: 'DEF' },
  { name: 'Yuto Nagatomo', team: 'Japan', position: 'DEF' },
  { name: 'Tsuyoshi Watanabe', team: 'Japan', position: 'DEF' },
  { name: 'Ayumu Seko', team: 'Japan', position: 'DEF' },
  { name: 'Hiroki Ito', team: 'Japan', position: 'DEF' },
  { name: 'Takehiro Tomiyasu', team: 'Japan', position: 'DEF' },
  { name: 'Junnosuke Suzuki', team: 'Japan', position: 'DEF' },
  { name: 'Wataru Endo', team: 'Japan', position: 'MEI' },
  { name: 'Ao Tanaka', team: 'Japan', position: 'MEI' },
  { name: 'Takefusa Kubo', team: 'Japan', position: 'MEI' },
  { name: 'Ritsu Doan', team: 'Japan', position: 'MEI' },
  { name: 'Daizen Maeda', team: 'Japan', position: 'MEI' },
  { name: 'Keito Nakamura', team: 'Japan', position: 'MEI' },
  { name: 'Junya Ito', team: 'Japan', position: 'MEI' },
  { name: 'Daichi Kamada', team: 'Japan', position: 'MEI' },
  { name: 'Yuito Suzuki', team: 'Japan', position: 'ATA' },
  { name: 'Kaishu Sano', team: 'Japan', position: 'ATA' },
  { name: 'Keisuke Goto', team: 'Japan', position: 'ATA' },
  { name: 'Ayase Ueda', team: 'Japan', position: 'ATA' },
  { name: 'Koki Ogawa', team: 'Japan', position: 'ATA' },
  { name: 'Kento Shiogai', team: 'Japan', position: 'ATA' },

  // Jordan
  { name: 'Yazeed Abu Laila', team: 'Jordan', position: 'GOL' },
  { name: 'Nour Baniateyah', team: 'Jordan', position: 'GOL' },
  { name: 'Abdallah Al-Fakhori', team: 'Jordan', position: 'GOL' },
  { name: 'Mohammad Abu Hasheesh', team: 'Jordan', position: 'DEF' },
  { name: 'Abdallah Nasib', team: 'Jordan', position: 'DEF' },
  { name: 'Husam Abu Dahab', team: 'Jordan', position: 'DEF' },
  { name: 'Yazan Al-Arab', team: 'Jordan', position: 'DEF' },
  { name: 'Mohammad Abu Al-Nadi', team: 'Jordan', position: 'DEF' },
  { name: 'Saleem Obaid', team: 'Jordan', position: 'DEF' },
  { name: 'Saed Al-Rosan', team: 'Jordan', position: 'DEF' },
  { name: 'Ehsan Haddad', team: 'Jordan', position: 'DEF' },
  { name: 'Anas Badawi', team: 'Jordan', position: 'MEI' },
  { name: 'Amer Jamous', team: 'Jordan', position: 'MEI' },
  { name: 'Noor Al-Rawabdeh', team: 'Jordan', position: 'MEI' },
  { name: 'Rajaei Ayed', team: 'Jordan', position: 'MEI' },
  { name: 'Ibrahim Sadeh', team: 'Jordan', position: 'MEI' },
  { name: 'Mohannad Abu Taha', team: 'Jordan', position: 'MEI' },
  { name: 'Nizar Al-Rashdan', team: 'Jordan', position: 'MEI' },
  { name: 'Mohammad Al-Daoud', team: 'Jordan', position: 'MEI' },
  { name: 'Mohammad Abu Zraiq', team: 'Jordan', position: 'MEI' },
  { name: 'Ali Olwan', team: 'Jordan', position: 'ATA' },
  { name: 'Mousa Al-Tamari', team: 'Jordan', position: 'ATA' },
  { name: 'Odeh Fakhoury', team: 'Jordan', position: 'ATA' },
  { name: 'Mahmoud Al-Mardi', team: 'Jordan', position: 'ATA' },
  { name: 'Ibrahim Sabra', team: 'Jordan', position: 'ATA' },
  { name: 'Ali Azaizeh', team: 'Jordan', position: 'ATA' },

  // Mexico
  { name: 'Raúl Rangel', team: 'Mexico', position: 'GOL' },
  { name: 'Carlos Acevedo', team: 'Mexico', position: 'GOL' },
  { name: 'Guillermo Ochoa', team: 'Mexico', position: 'GOL' },
  { name: 'Jorge Sánchez', team: 'Mexico', position: 'DEF' },
  { name: 'César Montes', team: 'Mexico', position: 'DEF' },
  { name: 'Edson Álvarez', team: 'Mexico', position: 'DEF' },
  { name: 'Johan Vásquez', team: 'Mexico', position: 'DEF' },
  { name: 'Israel Reyes', team: 'Mexico', position: 'DEF' },
  { name: 'Mateo Chávez', team: 'Mexico', position: 'DEF' },
  { name: 'Jesús Gallardo', team: 'Mexico', position: 'DEF' },
  { name: 'Erik Lira', team: 'Mexico', position: 'MEI' },
  { name: 'Luis Romo', team: 'Mexico', position: 'MEI' },
  { name: 'Álvaro Fidalgo', team: 'Mexico', position: 'MEI' },
  { name: 'Orbelín Piñeda', team: 'Mexico', position: 'MEI' },
  { name: 'Obed Vargas', team: 'Mexico', position: 'MEI' },
  { name: 'Gilberto Mora', team: 'Mexico', position: 'MEI' },
  { name: 'Luis Chávez', team: 'Mexico', position: 'MEI' },
  { name: 'Brian Gutiérrez', team: 'Mexico', position: 'MEI' },
  { name: 'Raúl Jiménez', team: 'Mexico', position: 'ATA' },
  { name: 'Alexis Vega', team: 'Mexico', position: 'ATA' },
  { name: 'Santiago Giménez', team: 'Mexico', position: 'ATA' },
  { name: 'Armando González', team: 'Mexico', position: 'ATA' },
  { name: 'Julián Quiñones', team: 'Mexico', position: 'ATA' },
  { name: 'César Huerta', team: 'Mexico', position: 'ATA' },
  { name: 'Guillermo Martínez', team: 'Mexico', position: 'ATA' },
  { name: 'Roberto Alvarado', team: 'Mexico', position: 'ATA' },

  // Panama
  { name: 'Luis Mejía', team: 'Panama', position: 'GOL' },
  { name: 'César Samudio', team: 'Panama', position: 'GOL' },
  { name: 'Orlando Mosquera', team: 'Panama', position: 'GOL' },
  { name: 'César Blackman', team: 'Panama', position: 'DEF' },
  { name: 'José Córdoba', team: 'Panama', position: 'DEF' },
  { name: 'Fidel Escobar', team: 'Panama', position: 'DEF' },
  { name: 'Edgardo Farina', team: 'Panama', position: 'DEF' },
  { name: 'Jiovany Ramos', team: 'Panama', position: 'DEF' },
  { name: 'Carlos Harvey', team: 'Panama', position: 'DEF' },
  { name: 'Eric Davis', team: 'Panama', position: 'DEF' },
  { name: 'Andrés Andrade', team: 'Panama', position: 'DEF' },
  { name: 'Amir Murillo', team: 'Panama', position: 'DEF' },
  { name: 'Roderick Miller', team: 'Panama', position: 'MEI' },
  { name: 'Jorge Gutiérrez', team: 'Panama', position: 'MEI' },
  { name: 'Cristian Martínez', team: 'Panama', position: 'MEI' },
  { name: 'José Rodríguez', team: 'Panama', position: 'MEI' },
  { name: 'Adalberto Carrasquilla', team: 'Panama', position: 'MEI' },
  { name: 'Ismael Díaz', team: 'Panama', position: 'MEI' },
  { name: 'Edgar Bárcenas', team: 'Panama', position: 'MEI' },
  { name: 'Alberto Quintero', team: 'Panama', position: 'ATA' },
  { name: 'Aníbal Godoy', team: 'Panama', position: 'ATA' },
  { name: 'César Yanis', team: 'Panama', position: 'ATA' },
  { name: 'Tomás Rodríguez', team: 'Panama', position: 'ATA' },
  { name: 'José Fajardo', team: 'Panama', position: 'ATA' },
  { name: 'Cecilio Waterman', team: 'Panama', position: 'ATA' },
  { name: 'Azarías Londoño', team: 'Panama', position: 'ATA' },

  // Paraguay
  { name: 'Roberto Fernández', team: 'Paraguay', position: 'GOL' },
  { name: 'Orlando Gill', team: 'Paraguay', position: 'GOL' },
  { name: 'Gastón Olveira', team: 'Paraguay', position: 'GOL' },
  { name: 'Gustavo Velázquez', team: 'Paraguay', position: 'DEF' },
  { name: 'Omar Alderete', team: 'Paraguay', position: 'DEF' },
  { name: 'Juan Cáceres', team: 'Paraguay', position: 'DEF' },
  { name: 'Fabián Balbuena', team: 'Paraguay', position: 'DEF' },
  { name: 'Junior Alonso', team: 'Paraguay', position: 'DEF' },
  { name: 'José Canale', team: 'Paraguay', position: 'DEF' },
  { name: 'Gustavo Gómez', team: 'Paraguay', position: 'DEF' },
  { name: 'Alexandro Maidana', team: 'Paraguay', position: 'DEF' },
  { name: 'Ramón Sosa', team: 'Paraguay', position: 'MEI' },
  { name: 'Diego Gómez', team: 'Paraguay', position: 'MEI' },
  { name: 'Miguel Almirón', team: 'Paraguay', position: 'MEI' },
  { name: 'Mauricio', team: 'Paraguay', position: 'MEI' },
  { name: 'Andrés Cubas', team: 'Paraguay', position: 'MEI' },
  { name: 'Damián Bobadilla', team: 'Paraguay', position: 'MEI' },
  { name: 'Braian Ojeda', team: 'Paraguay', position: 'MEI' },
  { name: 'Matías Galarza', team: 'Paraguay', position: 'MEI' },
  { name: 'Gustavo Caballero', team: 'Paraguay', position: 'MEI' },
  { name: 'Antonio Sanabria', team: 'Paraguay', position: 'ATA' },
  { name: 'Alejandro Romero', team: 'Paraguay', position: 'ATA' },
  { name: 'Álex Arce', team: 'Paraguay', position: 'ATA' },
  { name: 'Julio Enciso', team: 'Paraguay', position: 'ATA' },
  { name: 'Gabriel Ávalos', team: 'Paraguay', position: 'ATA' },
  { name: 'Isidro Pitta', team: 'Paraguay', position: 'ATA' },

  // Morocco
  { name: 'Yassine Bounou', team: 'Morocco', position: 'GOL' },
  { name: 'Munir El Kajoui', team: 'Morocco', position: 'GOL' },
  { name: 'Ahmed Tagnaouti', team: 'Morocco', position: 'GOL' },
  { name: 'Achraf Hakimi', team: 'Morocco', position: 'DEF' },
  { name: 'Noussair Mazraoui', team: 'Morocco', position: 'DEF' },
  { name: 'Nayef Aguerd', team: 'Morocco', position: 'DEF' },
  { name: 'Zakaria El Ouahdi', team: 'Morocco', position: 'DEF' },
  { name: 'Issa Diop', team: 'Morocco', position: 'DEF' },
  { name: 'Chadi Riad', team: 'Morocco', position: 'DEF' },
  { name: 'Youssef Belammari', team: 'Morocco', position: 'DEF' },
  { name: 'Redouane Halhal', team: 'Morocco', position: 'DEF' },
  { name: 'Anass Salah-Eddine', team: 'Morocco', position: 'DEF' },
  { name: 'Sofyan Amrabat', team: 'Morocco', position: 'MEI' },
  { name: 'Ayyoub Bouaddi', team: 'Morocco', position: 'MEI' },
  { name: 'Chemsdine Talbi', team: 'Morocco', position: 'MEI' },
  { name: 'Azzedine Ounahi', team: 'Morocco', position: 'MEI' },
  { name: 'Ismaël Saibari', team: 'Morocco', position: 'MEI' },
  { name: 'Samir El Mourabet', team: 'Morocco', position: 'MEI' },
  { name: 'Gessime Yassine', team: 'Morocco', position: 'MEI' },
  { name: 'Bilal El Khannouss', team: 'Morocco', position: 'MEI' },
  { name: 'Neil El Aynaoui', team: 'Morocco', position: 'MEI' },
  { name: 'Soufiane Rahimi', team: 'Morocco', position: 'ATA' },
  { name: 'Brahim Díaz', team: 'Morocco', position: 'ATA' },
  { name: 'Abde Ezzalzouli', team: 'Morocco', position: 'ATA' },
  { name: 'Ayoub El Kaabi', team: 'Morocco', position: 'ATA' },
  { name: 'Ayoub Amaimouni', team: 'Morocco', position: 'ATA' },

  // Netherlands
  { name: 'Bart Verbruggen', team: 'Netherlands', position: 'GOL' },
  { name: 'Robin Roefs', team: 'Netherlands', position: 'GOL' },
  { name: 'Mark Flekken', team: 'Netherlands', position: 'GOL' },
  { name: 'Jurriën Timber', team: 'Netherlands', position: 'DEF' },
  { name: 'Virgil van Dijk', team: 'Netherlands', position: 'DEF' },
  { name: 'Nathan Aké', team: 'Netherlands', position: 'DEF' },
  { name: 'Jan-Paul van Hecke', team: 'Netherlands', position: 'DEF' },
  { name: 'Mats Wieffer', team: 'Netherlands', position: 'DEF' },
  { name: 'Micky van de Ven', team: 'Netherlands', position: 'DEF' },
  { name: 'Denzel Dumfries', team: 'Netherlands', position: 'DEF' },
  { name: 'Jorrel Hato', team: 'Netherlands', position: 'DEF' },
  { name: 'Marten de Roon', team: 'Netherlands', position: 'MEI' },
  { name: 'Justin Kluivert', team: 'Netherlands', position: 'MEI' },
  { name: 'Ryan Gravenberch', team: 'Netherlands', position: 'MEI' },
  { name: 'Tijjani Reijnders', team: 'Netherlands', position: 'MEI' },
  { name: 'Guus Til', team: 'Netherlands', position: 'MEI' },
  { name: 'Teun Koopmeiners', team: 'Netherlands', position: 'MEI' },
  { name: 'Frenkie de Jong', team: 'Netherlands', position: 'MEI' },
  { name: 'Quinten Timber', team: 'Netherlands', position: 'MEI' },
  { name: 'Wout Weghorst', team: 'Netherlands', position: 'ATA' },
  { name: 'Memphis Depay', team: 'Netherlands', position: 'ATA' },
  { name: 'Cody Gakpo', team: 'Netherlands', position: 'ATA' },
  { name: 'Noa Lang', team: 'Netherlands', position: 'ATA' },
  { name: 'Donyell Malen', team: 'Netherlands', position: 'ATA' },
  { name: 'Brian Brobbey', team: 'Netherlands', position: 'ATA' },
  { name: 'Crysencio Summerville', team: 'Netherlands', position: 'ATA' },

  // Saudi Arabia
  { name: 'Nawaf Al-Aqidi', team: 'Saudi Arabia', position: 'GOL' },
  { name: 'Mohammed Al-Owais', team: 'Saudi Arabia', position: 'GOL' },
  { name: 'Ahmed Al-Kassar', team: 'Saudi Arabia', position: 'GOL' },
  { name: 'Ali Majrashi', team: 'Saudi Arabia', position: 'DEF' },
  { name: 'Ali Lajami', team: 'Saudi Arabia', position: 'DEF' },
  { name: 'Abdulelah Al-Amri', team: 'Saudi Arabia', position: 'DEF' },
  { name: 'Hassan Al-Tambakti', team: 'Saudi Arabia', position: 'DEF' },
  { name: 'Saud Abdulhamid', team: 'Saudi Arabia', position: 'DEF' },
  { name: 'Nawaf Bu Washl', team: 'Saudi Arabia', position: 'DEF' },
  { name: 'Hassan Kadish', team: 'Saudi Arabia', position: 'DEF' },
  { name: 'Moteb Al-Harbi', team: 'Saudi Arabia', position: 'DEF' },
  { name: 'Jehad Thikri', team: 'Saudi Arabia', position: 'MEI' },
  { name: 'Mohammed Abu Alshamat', team: 'Saudi Arabia', position: 'MEI' },
  { name: 'Nasser Al-Dawsari', team: 'Saudi Arabia', position: 'MEI' },
  { name: 'Musab Al-Juwayr', team: 'Saudi Arabia', position: 'MEI' },
  { name: 'Abdullah Al-Khaibari', team: 'Saudi Arabia', position: 'MEI' },
  { name: 'Ziyad Al-Johani', team: 'Saudi Arabia', position: 'MEI' },
  { name: 'Ala Al-Hajji', team: 'Saudi Arabia', position: 'MEI' },
  { name: 'Mohamed Kanno', team: 'Saudi Arabia', position: 'MEI' },
  { name: 'Aiman Yahya', team: 'Saudi Arabia', position: 'MEI' },
  { name: 'Feras Al-Brikan', team: 'Saudi Arabia', position: 'ATA' },
  { name: 'Salem Al-Dawsari', team: 'Saudi Arabia', position: 'ATA' },
  { name: 'Saleh Al-Shehri', team: 'Saudi Arabia', position: 'ATA' },
  { name: 'Khalid Al-Ghannam', team: 'Saudi Arabia', position: 'ATA' },
  { name: 'Abdullah Al-Hamddan', team: 'Saudi Arabia', position: 'ATA' },
  { name: 'Sultan Mandash', team: 'Saudi Arabia', position: 'ATA' },

  // Norway
  { name: 'Ørjan Nyland', team: 'Norway', position: 'GOL' },
  { name: 'Sander Tangvik', team: 'Norway', position: 'GOL' },
  { name: 'Egil Selvik', team: 'Norway', position: 'GOL' },
  { name: 'Kristoffer Ajer', team: 'Norway', position: 'DEF' },
  { name: 'Leo Østigård', team: 'Norway', position: 'DEF' },
  { name: 'David Wolfe', team: 'Norway', position: 'DEF' },
  { name: 'Fredrik Bjørkan', team: 'Norway', position: 'DEF' },
  { name: 'Marcus Pedersen', team: 'Norway', position: 'DEF' },
  { name: 'Torbjørn Heggem', team: 'Norway', position: 'DEF' },
  { name: 'Sondre Langas', team: 'Norway', position: 'DEF' },
  { name: 'Henrik Falchener', team: 'Norway', position: 'DEF' },
  { name: 'Morten Thorsby', team: 'Norway', position: 'MEI' },
  { name: 'Patrick Berg', team: 'Norway', position: 'MEI' },
  { name: 'Sander Berge', team: 'Norway', position: 'MEI' },
  { name: 'Martin Ødegaard', team: 'Norway', position: 'MEI' },
  { name: 'Fredrik Aursnes', team: 'Norway', position: 'MEI' },
  { name: 'Kristian Thorstvedt', team: 'Norway', position: 'MEI' },
  { name: 'Thelo Aasgaard', team: 'Norway', position: 'MEI' },
  { name: 'Andreas Schjelderup', team: 'Norway', position: 'ATA' },
  { name: 'Oscar Bobb', team: 'Norway', position: 'ATA' },
  { name: 'Jens Hauge', team: 'Norway', position: 'ATA' },
  { name: 'Alexander Sørloth', team: 'Norway', position: 'ATA' },
  { name: 'Erling Haaland', team: 'Norway', position: 'ATA' },
  { name: 'Jørgen Larsen', team: 'Norway', position: 'ATA' },
  { name: 'Antonio Nusa', team: 'Norway', position: 'ATA' },
  { name: 'Julian Ryerson', team: 'Norway', position: 'DEF' },

  // Portugal
  { name: 'Diogo Costa', team: 'Portugal', position: 'GOL' },
  { name: 'José Sá', team: 'Portugal', position: 'GOL' },
  { name: 'Rui Silva', team: 'Portugal', position: 'GOL' },
  { name: 'Nelson Semedo', team: 'Portugal', position: 'DEF' },
  { name: 'Rúben Dias', team: 'Portugal', position: 'DEF' },
  { name: 'Tomás Araújo', team: 'Portugal', position: 'DEF' },
  { name: 'Diogo Dalot', team: 'Portugal', position: 'DEF' },
  { name: 'Renato Veiga', team: 'Portugal', position: 'DEF' },
  { name: 'Gonçalo Inácio', team: 'Portugal', position: 'DEF' },
  { name: 'João Cancelo', team: 'Portugal', position: 'DEF' },
  { name: 'Samu Costa', team: 'Portugal', position: 'DEF' },
  { name: 'Nuno Mendes', team: 'Portugal', position: 'DEF' },
  { name: 'Matheus Nunes', team: 'Portugal', position: 'MEI' },
  { name: 'Bruno Fernandes', team: 'Portugal', position: 'MEI' },
  { name: 'Bernardo Silva', team: 'Portugal', position: 'MEI' },
  { name: 'João Neves', team: 'Portugal', position: 'MEI' },
  { name: 'Rúben Neves', team: 'Portugal', position: 'MEI' },
  { name: 'Vítor Ferreira', team: 'Portugal', position: 'MEI' },
  { name: 'Cristiano Ronaldo', team: 'Portugal', position: 'ATA' },
  { name: 'Gonçalo Ramos', team: 'Portugal', position: 'ATA' },
  { name: 'João Félix', team: 'Portugal', position: 'ATA' },
  { name: 'Francisco Trincão', team: 'Portugal', position: 'ATA' },
  { name: 'Rafael Leão', team: 'Portugal', position: 'ATA' },
  { name: 'Pedro Neto', team: 'Portugal', position: 'ATA' },
  { name: 'Gonçalo Guedes', team: 'Portugal', position: 'ATA' },
  { name: 'Francisco Conceição', team: 'Portugal', position: 'ATA' },

  // New Zealand
  { name: 'Max Crocombe', team: 'New Zealand', position: 'GOL' },
  { name: 'Alex Paulsen', team: 'New Zealand', position: 'GOL' },
  { name: 'Michael Woud', team: 'New Zealand', position: 'GOL' },
  { name: 'Tyler Bindon', team: 'New Zealand', position: 'DEF' },
  { name: 'Michael Boxall', team: 'New Zealand', position: 'DEF' },
  { name: 'Liberato Cacace', team: 'New Zealand', position: 'DEF' },
  { name: 'Francis de Vries', team: 'New Zealand', position: 'DEF' },
  { name: 'Callan Elliot', team: 'New Zealand', position: 'DEF' },
  { name: 'Tim Payne', team: 'New Zealand', position: 'DEF' },
  { name: 'Nando Pijnaker', team: 'New Zealand', position: 'DEF' },
  { name: 'Tommy Smith', team: 'New Zealand', position: 'DEF' },
  { name: 'Finn Surman', team: 'New Zealand', position: 'DEF' },
  { name: 'Lachlan Bayliss', team: 'New Zealand', position: 'MEI' },
  { name: 'Joe Bell', team: 'New Zealand', position: 'MEI' },
  { name: 'Matt Garbett', team: 'New Zealand', position: 'MEI' },
  { name: 'Ben Old', team: 'New Zealand', position: 'MEI' },
  { name: 'Alex Rufer', team: 'New Zealand', position: 'MEI' },
  { name: 'Sarpreet Singh', team: 'New Zealand', position: 'MEI' },
  { name: 'Marko Stamenic', team: 'New Zealand', position: 'MEI' },
  { name: 'Ryan Thomas', team: 'New Zealand', position: 'MEI' },
  { name: 'Kosta Barbarouses', team: 'New Zealand', position: 'ATA' },
  { name: 'Eli Just', team: 'New Zealand', position: 'ATA' },
  { name: 'Callum McCowatt', team: 'New Zealand', position: 'ATA' },
  { name: 'Jesse Randall', team: 'New Zealand', position: 'ATA' },
  { name: 'Ben Waine', team: 'New Zealand', position: 'ATA' },
  { name: 'Chris Wood', team: 'New Zealand', position: 'ATA' },

  // Senegal
  { name: 'Yehvann Diouf', team: 'Senegal', position: 'GOL' },
  { name: 'Édouard Mendy', team: 'Senegal', position: 'GOL' },
  { name: 'Mory Diaw', team: 'Senegal', position: 'GOL' },
  { name: 'Mamadou Sarr', team: 'Senegal', position: 'DEF' },
  { name: 'Kalidou Koulibaly', team: 'Senegal', position: 'DEF' },
  { name: 'Abdoulaye Seck', team: 'Senegal', position: 'DEF' },
  { name: 'Ismail Jakobs', team: 'Senegal', position: 'DEF' },
  { name: 'Krepin Diatta', team: 'Senegal', position: 'DEF' },
  { name: 'Moussa Niakhaté', team: 'Senegal', position: 'DEF' },
  { name: 'Antoine Mendy', team: 'Senegal', position: 'DEF' },
  { name: 'El Hadji Diouf', team: 'Senegal', position: 'DEF' },
  { name: 'Idrissa Gueye', team: 'Senegal', position: 'MEI' },
  { name: 'Pathé Ciss', team: 'Senegal', position: 'MEI' },
  { name: 'Lamine Camara', team: 'Senegal', position: 'MEI' },
  { name: 'Pape Sarr', team: 'Senegal', position: 'MEI' },
  { name: 'Habib Diarra', team: 'Senegal', position: 'MEI' },
  { name: 'Bara Ndiaye', team: 'Senegal', position: 'MEI' },
  { name: 'Pape Gueye', team: 'Senegal', position: 'MEI' },
  { name: 'Assane Diao', team: 'Senegal', position: 'ATA' },
  { name: 'Bamba Dieng', team: 'Senegal', position: 'ATA' },
  { name: 'Sadio Mané', team: 'Senegal', position: 'ATA' },
  { name: 'Nicolas Jackson', team: 'Senegal', position: 'ATA' },
  { name: 'Chérif Ndiaye', team: 'Senegal', position: 'ATA' },
  { name: 'Iliman Ndiaye', team: 'Senegal', position: 'ATA' },
  { name: 'Ismaïla Sarr', team: 'Senegal', position: 'ATA' },
  { name: 'Ibrahim Mbaye', team: 'Senegal', position: 'ATA' },

  // Tunisia
  { name: 'Mouhib Chamakh', team: 'Tunisia', position: 'GOL' },
  { name: 'Aymen Dahmen', team: 'Tunisia', position: 'GOL' },
  { name: 'Sabri Ben Hessen', team: 'Tunisia', position: 'GOL' },
  { name: 'Ali Abdi', team: 'Tunisia', position: 'DEF' },
  { name: 'Montassar Talbi', team: 'Tunisia', position: 'DEF' },
  { name: 'Omar Rekik', team: 'Tunisia', position: 'DEF' },
  { name: 'Adam Arous', team: 'Tunisia', position: 'DEF' },
  { name: 'Dylan Bronn', team: 'Tunisia', position: 'DEF' },
  { name: 'Mortadha Ben Ouanes', team: 'Tunisia', position: 'DEF' },
  { name: 'Yan Valery', team: 'Tunisia', position: 'DEF' },
  { name: 'Mohamed Ben Hmida', team: 'Tunisia', position: 'DEF' },
  { name: 'Moutaz Neffati', team: 'Tunisia', position: 'DEF' },
  { name: 'Raed Chikhaoui', team: 'Tunisia', position: 'MEI' },
  { name: 'Hannibal Mejbri', team: 'Tunisia', position: 'MEI' },
  { name: 'Ismaël Gharbi', team: 'Tunisia', position: 'MEI' },
  { name: 'Rani Khedira', team: 'Tunisia', position: 'MEI' },
  { name: 'Khalil Ayari', team: 'Tunisia', position: 'MEI' },
  { name: 'Mohamed Hadj Mahmoud', team: 'Tunisia', position: 'MEI' },
  { name: 'Ellyes Skhiri', team: 'Tunisia', position: 'MEI' },
  { name: 'Anis Slimane', team: 'Tunisia', position: 'MEI' },
  { name: 'Sebastian Tounekti', team: 'Tunisia', position: 'ATA' },
  { name: 'Elias Achouri', team: 'Tunisia', position: 'ATA' },
  { name: 'Elias Saad', team: 'Tunisia', position: 'ATA' },
  { name: 'Hazem Mastouri', team: 'Tunisia', position: 'ATA' },
  { name: 'Rayan Elloumi', team: 'Tunisia', position: 'ATA' },
  { name: 'Firas Chaouat', team: 'Tunisia', position: 'ATA' },

  // Serbia
  { name: 'Dusan Vlahovic', team: 'Serbia', position: 'ATA' },
  { name: 'Aleksandar Mitrovic', team: 'Serbia', position: 'ATA' },

  // South Korea
  { name: 'Seunggyu Kim', team: 'South Korea', position: 'GOL' },
  { name: 'Bumkeun Song', team: 'South Korea', position: 'GOL' },
  { name: 'Hyeonwoo Jo', team: 'South Korea', position: 'GOL' },
  { name: 'Hanbeom Lee', team: 'South Korea', position: 'DEF' },
  { name: 'Minjae Kim', team: 'South Korea', position: 'DEF' },
  { name: 'Taehyeon Kim', team: 'South Korea', position: 'DEF' },
  { name: 'Taeseok Lee', team: 'South Korea', position: 'DEF' },
  { name: 'Wije Cho', team: 'South Korea', position: 'DEF' },
  { name: 'Moonhwan Kim', team: 'South Korea', position: 'DEF' },
  { name: 'Jinseob Park', team: 'South Korea', position: 'DEF' },
  { name: 'Youngwoo Seol', team: 'South Korea', position: 'DEF' },
  { name: 'Jens Castrop', team: 'South Korea', position: 'MEI' },
  { name: 'Gihyuk Lee', team: 'South Korea', position: 'MEI' },
  { name: 'Inbeom Hwang', team: 'South Korea', position: 'MEI' },
  { name: 'Seungho Paik', team: 'South Korea', position: 'MEI' },
  { name: 'Jaesung Lee', team: 'South Korea', position: 'MEI' },
  { name: 'Heechan Hwang', team: 'South Korea', position: 'MEI' },
  { name: 'Junho Bae', team: 'South Korea', position: 'MEI' },
  { name: 'Kangin Lee', team: 'South Korea', position: 'MEI' },
  { name: 'Hyunjun Yang', team: 'South Korea', position: 'ATA' },
  { name: 'Jingyu Kim', team: 'South Korea', position: 'ATA' },
  { name: 'Jisung Eom', team: 'South Korea', position: 'ATA' },
  { name: 'Donggyeong Lee', team: 'South Korea', position: 'ATA' },
  { name: 'Heungmin Son', team: 'South Korea', position: 'ATA' },
  { name: 'Guesung Cho', team: 'South Korea', position: 'ATA' },
  { name: 'Hyeongyu Oh', team: 'South Korea', position: 'ATA' },

  // South Africa
  { name: 'Ronwen Williams', team: 'South Africa', position: 'GOL' },
  { name: 'Sipho Chaine', team: 'South Africa', position: 'GOL' },
  { name: 'Ricardo Goss', team: 'South Africa', position: 'GOL' },
  { name: 'Thabang Matuludi', team: 'South Africa', position: 'DEF' },
  { name: 'Khulumani Ndamane', team: 'South Africa', position: 'DEF' },
  { name: 'Aubrey Modiba', team: 'South Africa', position: 'DEF' },
  { name: 'Mbekezeli Mbokazi', team: 'South Africa', position: 'DEF' },
  { name: 'Samukelo Kabini', team: 'South Africa', position: 'DEF' },
  { name: 'Nkosinathi Sibisi', team: 'South Africa', position: 'DEF' },
  { name: 'Khuliso Mudau', team: 'South Africa', position: 'DEF' },
  { name: 'Ime Okon', team: 'South Africa', position: 'DEF' },
  { name: 'Olwethu Makhanya', team: 'South Africa', position: 'DEF' },
  { name: 'Bradley Cross', team: 'South Africa', position: 'DEF' },
  { name: 'Teboho Mokoena', team: 'South Africa', position: 'MEI' },
  { name: 'Thalente Mbatha', team: 'South Africa', position: 'MEI' },
  { name: 'Themba Zwane', team: 'South Africa', position: 'MEI' },
  { name: 'Sphephelo Sithole', team: 'South Africa', position: 'MEI' },
  { name: 'Jayden Adams', team: 'South Africa', position: 'MEI' },
  { name: 'Oswin Appollis', team: 'South Africa', position: 'ATA' },
  { name: 'Tshepang Moremi', team: 'South Africa', position: 'ATA' },
  { name: 'Lyle Foster', team: 'South Africa', position: 'ATA' },
  { name: 'Relebohile Mofokeng', team: 'South Africa', position: 'ATA' },
  { name: 'Thapelo Maseko', team: 'South Africa', position: 'ATA' },
  { name: 'Iqraam Rayners', team: 'South Africa', position: 'ATA' },
  { name: 'Evidence Makgopa', team: 'South Africa', position: 'ATA' },
  { name: 'Kamogelo Sebelebele', team: 'South Africa', position: 'ATA' },

  // Scotland
  { name: 'Angus Gunn', team: 'Scotland', position: 'GOL' },
  { name: 'Liam Kelly', team: 'Scotland', position: 'GOL' },
  { name: 'Craig Gordon', team: 'Scotland', position: 'GOL' },
  { name: 'Aaron Hickey', team: 'Scotland', position: 'DEF' },
  { name: 'Andy Robertson', team: 'Scotland', position: 'DEF' },
  { name: 'Grant Hanley', team: 'Scotland', position: 'DEF' },
  { name: 'Kieran Tierney', team: 'Scotland', position: 'DEF' },
  { name: 'Jack Hendry', team: 'Scotland', position: 'DEF' },
  { name: 'John Souttar', team: 'Scotland', position: 'DEF' },
  { name: 'Dominic Hyam', team: 'Scotland', position: 'DEF' },
  { name: 'Nathan Patterson', team: 'Scotland', position: 'DEF' },
  { name: 'Anthony Ralston', team: 'Scotland', position: 'DEF' },
  { name: 'Scott McKenna', team: 'Scotland', position: 'DEF' },
  { name: 'Scott McTominay', team: 'Scotland', position: 'MEI' },
  { name: 'John McGinn', team: 'Scotland', position: 'MEI' },
  { name: 'Tyler Fletcher', team: 'Scotland', position: 'MEI' },
  { name: 'Ryan Christie', team: 'Scotland', position: 'MEI' },
  { name: 'Lewis Ferguson', team: 'Scotland', position: 'MEI' },
  { name: 'Kenny McLean', team: 'Scotland', position: 'MEI' },
  { name: 'Lyndon Dykes', team: 'Scotland', position: 'ATA' },
  { name: 'Che Adams', team: 'Scotland', position: 'ATA' },
  { name: 'Ross Stewart', team: 'Scotland', position: 'ATA' },
  { name: 'Ben Doak', team: 'Scotland', position: 'ATA' },
  { name: 'George Hirst', team: 'Scotland', position: 'ATA' },
  { name: 'Lawrence Shankland', team: 'Scotland', position: 'ATA' },
  { name: 'Findlay Curtis', team: 'Scotland', position: 'ATA' },

  // Spain
  { name: 'David Raya', team: 'Spain', position: 'GOL' },
  { name: 'Joan García', team: 'Spain', position: 'GOL' },
  { name: 'Unai Simón', team: 'Spain', position: 'GOL' },
  { name: 'Marc Pubill', team: 'Spain', position: 'DEF' },
  { name: 'Álex Grimaldo', team: 'Spain', position: 'DEF' },
  { name: 'Eric García', team: 'Spain', position: 'DEF' },
  { name: 'Marcos Llorente', team: 'Spain', position: 'DEF' },
  { name: 'Pedro Porro', team: 'Spain', position: 'DEF' },
  { name: 'Aymeric Laporte', team: 'Spain', position: 'DEF' },
  { name: 'Pau Cubarsí', team: 'Spain', position: 'DEF' },
  { name: 'Marc Cucurella', team: 'Spain', position: 'DEF' },
  { name: 'Mikel Merino', team: 'Spain', position: 'MEI' },
  { name: 'Fabián Ruiz', team: 'Spain', position: 'MEI' },
  { name: 'Pablo Gavira', team: 'Spain', position: 'MEI' },
  { name: 'Álex Baena', team: 'Spain', position: 'MEI' },
  { name: 'Rodrigo Hernández', team: 'Spain', position: 'MEI' },
  { name: 'Martín Zubimendi', team: 'Spain', position: 'MEI' },
  { name: 'Pedro López', team: 'Spain', position: 'MEI' },
  { name: 'Ferran Torres', team: 'Spain', position: 'ATA' },
  { name: 'Dani Olmo', team: 'Spain', position: 'ATA' },
  { name: 'Yeremy Pino', team: 'Spain', position: 'ATA' },
  { name: 'Nico Williams', team: 'Spain', position: 'ATA' },
  { name: 'Lamine Yamal', team: 'Spain', position: 'ATA' },
  { name: 'Mikel Oyarzabal', team: 'Spain', position: 'ATA' },
  { name: 'Víctor Muñoz', team: 'Spain', position: 'ATA' },
  { name: 'Borja Iglesias', team: 'Spain', position: 'ATA' },

  // Sweden
  { name: 'Jacob Zetterström', team: 'Sweden', position: 'GOL' },
  { name: 'Viktor Johansson', team: 'Sweden', position: 'GOL' },
  { name: 'Kristoffer Nordfeldt', team: 'Sweden', position: 'GOL' },
  { name: 'Gustaf Lagerbielke', team: 'Sweden', position: 'DEF' },
  { name: 'Victor Lindelöf', team: 'Sweden', position: 'DEF' },
  { name: 'Isak Hien', team: 'Sweden', position: 'DEF' },
  { name: 'Gabriel Gudmundsson', team: 'Sweden', position: 'DEF' },
  { name: 'Herman Johansson', team: 'Sweden', position: 'DEF' },
  { name: 'Daniel Svensson', team: 'Sweden', position: 'DEF' },
  { name: 'Hjalmar Ekdal', team: 'Sweden', position: 'DEF' },
  { name: 'Carl Starfelt', team: 'Sweden', position: 'DEF' },
  { name: 'Eric Smith', team: 'Sweden', position: 'MEI' },
  { name: 'Alexander Bernhardsson', team: 'Sweden', position: 'MEI' },
  { name: 'Elliot Stroud', team: 'Sweden', position: 'MEI' },
  { name: 'Lucas Bergvall', team: 'Sweden', position: 'MEI' },
  { name: 'Benjamin Nygren', team: 'Sweden', position: 'MEI' },
  { name: 'Ken Sema', team: 'Sweden', position: 'MEI' },
  { name: 'Jesper Karlström', team: 'Sweden', position: 'MEI' },
  { name: 'Yasin Ayari', team: 'Sweden', position: 'MEI' },
  { name: 'Mattias Svanberg', team: 'Sweden', position: 'MEI' },
  { name: 'Besfort Zeneli', team: 'Sweden', position: 'ATA' },
  { name: 'Alexander Isak', team: 'Sweden', position: 'ATA' },
  { name: 'Anthony Elanga', team: 'Sweden', position: 'ATA' },
  { name: 'Viktor Gyökeres', team: 'Sweden', position: 'ATA' },
  { name: 'Gustaf Nilsson', team: 'Sweden', position: 'ATA' },
  { name: 'Taha Ali', team: 'Sweden', position: 'ATA' },

  // Switzerland
  { name: 'Gregor Kobel', team: 'Switzerland', position: 'GOL' },
  { name: 'Yvon Mvogo', team: 'Switzerland', position: 'GOL' },
  { name: 'Marvin Keller', team: 'Switzerland', position: 'GOL' },
  { name: 'Miro Muheim', team: 'Switzerland', position: 'DEF' },
  { name: 'Silvan Widmer', team: 'Switzerland', position: 'DEF' },
  { name: 'Nico Elvedi', team: 'Switzerland', position: 'DEF' },
  { name: 'Manuel Akanji', team: 'Switzerland', position: 'DEF' },
  { name: 'Ricardo Rodríguez', team: 'Switzerland', position: 'DEF' },
  { name: 'Eray Cömert', team: 'Switzerland', position: 'DEF' },
  { name: 'Aurèle Amenda', team: 'Switzerland', position: 'DEF' },
  { name: 'Luca Jaquez', team: 'Switzerland', position: 'DEF' },
  { name: 'Denis Zakaria', team: 'Switzerland', position: 'MEI' },
  { name: 'Remo Freuler', team: 'Switzerland', position: 'MEI' },
  { name: 'Johan Manzambi', team: 'Switzerland', position: 'MEI' },
  { name: 'Granit Xhaka', team: 'Switzerland', position: 'MEI' },
  { name: 'Ardon Jashari', team: 'Switzerland', position: 'MEI' },
  { name: 'Djibril Sow', team: 'Switzerland', position: 'MEI' },
  { name: 'Michel Aebischer', team: 'Switzerland', position: 'MEI' },
  { name: 'Fabian Rieder', team: 'Switzerland', position: 'MEI' },
  { name: 'Breel Embolo', team: 'Switzerland', position: 'ATA' },
  { name: 'Dan Ndoye', team: 'Switzerland', position: 'ATA' },
  { name: 'Christian Fassnacht', team: 'Switzerland', position: 'ATA' },
  { name: 'Rubén Vargas', team: 'Switzerland', position: 'ATA' },
  { name: 'Noah Okafor', team: 'Switzerland', position: 'ATA' },
  { name: 'Zeki Amdouni', team: 'Switzerland', position: 'ATA' },
  { name: 'Cédric Itten', team: 'Switzerland', position: 'ATA' },

  // United States
  { name: 'Matt Turner', team: 'United States', position: 'GOL' },
  { name: 'Matt Freese', team: 'United States', position: 'GOL' },
  { name: 'Chris Brady', team: 'United States', position: 'GOL' },
  { name: 'Sergiño Dest', team: 'United States', position: 'DEF' },
  { name: 'Chris Richards', team: 'United States', position: 'DEF' },
  { name: 'Antonee Robinson', team: 'United States', position: 'DEF' },
  { name: 'Auston Trusty', team: 'United States', position: 'DEF' },
  { name: 'Miles Robinson', team: 'United States', position: 'DEF' },
  { name: 'Tim Ream', team: 'United States', position: 'DEF' },
  { name: 'Alex Freeman', team: 'United States', position: 'DEF' },
  { name: 'Max Arfsten', team: 'United States', position: 'DEF' },
  { name: 'Mark McKenzie', team: 'United States', position: 'DEF' },
  { name: 'Joe Scally', team: 'United States', position: 'DEF' },
  { name: 'Tyler Adams', team: 'United States', position: 'MEI' },
  { name: 'Giovanni Reyna', team: 'United States', position: 'MEI' },
  { name: 'Weston McKennie', team: 'United States', position: 'MEI' },
  { name: 'Sebastian Berhalter', team: 'United States', position: 'MEI' },
  { name: 'Cristian Roldán', team: 'United States', position: 'MEI' },
  { name: 'Malik Tillman', team: 'United States', position: 'MEI' },
  { name: 'Ricardo Pepi', team: 'United States', position: 'ATA' },
  { name: 'Christian Pulisic', team: 'United States', position: 'ATA' },
  { name: 'Brenden Aaronson', team: 'United States', position: 'ATA' },
  { name: 'Haji Wright', team: 'United States', position: 'ATA' },
  { name: 'Folarin Balogun', team: 'United States', position: 'ATA' },
  { name: 'Timothy Weah', team: 'United States', position: 'ATA' },
  { name: 'Alex Zendejas', team: 'United States', position: 'ATA' },

  // Uzbekistan
  { name: 'Utkir Yusupov', team: 'Uzbekistan', position: 'GOL' },
  { name: 'Abduvohid Nematov', team: 'Uzbekistan', position: 'GOL' },
  { name: 'Botirali Ergashev', team: 'Uzbekistan', position: 'GOL' },
  { name: 'Abdukodir Khusanov', team: 'Uzbekistan', position: 'DEF' },
  { name: 'Khojiakbar Alijonov', team: 'Uzbekistan', position: 'DEF' },
  { name: 'Farrukh Sayfiev', team: 'Uzbekistan', position: 'DEF' },
  { name: 'Rustam Ashurmatov', team: 'Uzbekistan', position: 'DEF' },
  { name: 'Sherzod Nasrullaev', team: 'Uzbekistan', position: 'DEF' },
  { name: 'Umar Eshmurodov', team: 'Uzbekistan', position: 'DEF' },
  { name: 'Abdulla Abdullaev', team: 'Uzbekistan', position: 'DEF' },
  { name: 'Behruzjon Karimov', team: 'Uzbekistan', position: 'DEF' },
  { name: 'Avazbek Ulmasaliyev', team: 'Uzbekistan', position: 'MEI' },
  { name: 'Jakhongir Urozov', team: 'Uzbekistan', position: 'MEI' },
  { name: 'Akmal Mozgovoy', team: 'Uzbekistan', position: 'MEI' },
  { name: 'Otabek Shukurov', team: 'Uzbekistan', position: 'MEI' },
  { name: 'Jamshid Iskanderov', team: 'Uzbekistan', position: 'MEI' },
  { name: 'Odiljon Xamrobekov', team: 'Uzbekistan', position: 'MEI' },
  { name: 'Jaloliddin Masharipov', team: 'Uzbekistan', position: 'MEI' },
  { name: 'Oston Urunov', team: 'Uzbekistan', position: 'MEI' },
  { name: 'Dostonbek Khamdamov', team: 'Uzbekistan', position: 'ATA' },
  { name: 'Azizjon Ganiev', team: 'Uzbekistan', position: 'ATA' },
  { name: 'Abbosbek Fayzullaev', team: 'Uzbekistan', position: 'ATA' },
  { name: 'Sherzod Esanov', team: 'Uzbekistan', position: 'ATA' },
  { name: 'Eldor Shomurodov', team: 'Uzbekistan', position: 'ATA' },
  { name: 'Azizbek Amonov', team: 'Uzbekistan', position: 'ATA' },
  { name: 'Igor Sergeev', team: 'Uzbekistan', position: 'ATA' },

  // Turkey
  { name: 'Mert Günok', team: 'Turkey', position: 'GOL' },
  { name: 'Altay Bayındır', team: 'Turkey', position: 'GOL' },
  { name: 'Uğurcan Çakır', team: 'Turkey', position: 'GOL' },
  { name: 'Zeki Çelik', team: 'Turkey', position: 'DEF' },
  { name: 'Merih Demiral', team: 'Turkey', position: 'DEF' },
  { name: 'Çağlar Söyüncü', team: 'Turkey', position: 'DEF' },
  { name: 'Eren Elmalı', team: 'Turkey', position: 'DEF' },
  { name: 'Abdülkerim Bardakçı', team: 'Turkey', position: 'DEF' },
  { name: 'Ozan Kabak', team: 'Turkey', position: 'DEF' },
  { name: 'Mert Müldür', team: 'Turkey', position: 'DEF' },
  { name: 'Ferdi Kadıoğlu', team: 'Turkey', position: 'DEF' },
  { name: 'Samet Akaydın', team: 'Turkey', position: 'DEF' },
  { name: 'Salih Özcan', team: 'Turkey', position: 'MEI' },
  { name: 'Orkun Kökcü', team: 'Turkey', position: 'MEI' },
  { name: 'Hakan Çalhanoğlu', team: 'Turkey', position: 'MEI' },
  { name: 'İsmail Yüksek', team: 'Turkey', position: 'MEI' },
  { name: 'Kaan Ayhan', team: 'Turkey', position: 'MEI' },
  { name: 'Kerem Aktürkoğlu', team: 'Turkey', position: 'ATA' },
  { name: 'Arda Güler', team: 'Turkey', position: 'ATA' },
  { name: 'Deniz Gül', team: 'Turkey', position: 'ATA' },
  { name: 'Kenan Yıldız', team: 'Turkey', position: 'ATA' },
  { name: 'İrfan Kahveci', team: 'Turkey', position: 'ATA' },
  { name: 'Yunus Akgün', team: 'Turkey', position: 'ATA' },
  { name: 'Barış Yılmaz', team: 'Turkey', position: 'ATA' },
  { name: 'Oğuz Aydın', team: 'Turkey', position: 'ATA' },
  { name: 'Can Uzun', team: 'Turkey', position: 'ATA' },

  // Uruguay
  { name: 'Sergio Rochet', team: 'Uruguay', position: 'GOL' },
  { name: 'Santiago Mele', team: 'Uruguay', position: 'GOL' },
  { name: 'Fernando Muslera', team: 'Uruguay', position: 'GOL' },
  { name: 'José Giménez', team: 'Uruguay', position: 'DEF' },
  { name: 'Sebastián Cáceres', team: 'Uruguay', position: 'DEF' },
  { name: 'Ronald Araújo', team: 'Uruguay', position: 'DEF' },
  { name: 'Guillermo Varela', team: 'Uruguay', position: 'DEF' },
  { name: 'Mathías Olivera', team: 'Uruguay', position: 'DEF' },
  { name: 'Matías Viña', team: 'Uruguay', position: 'DEF' },
  { name: 'Santiago Bueno', team: 'Uruguay', position: 'DEF' },
  { name: 'Manuel Ugarte', team: 'Uruguay', position: 'MEI' },
  { name: 'Rodrigo Bentancur', team: 'Uruguay', position: 'MEI' },
  { name: 'Nicolás de la Cruz', team: 'Uruguay', position: 'MEI' },
  { name: 'Federico Valverde', team: 'Uruguay', position: 'MEI' },
  { name: 'Giorgian de Arrascaeta', team: 'Uruguay', position: 'MEI' },
  { name: 'Agustín Canobbio', team: 'Uruguay', position: 'MEI' },
  { name: 'Emiliano Martínez', team: 'Uruguay', position: 'MEI' },
  { name: 'Maximiliano Araújo', team: 'Uruguay', position: 'MEI' },
  { name: 'Joaquín Piquerez', team: 'Uruguay', position: 'DEF' },
  { name: 'Juan Sanabria', team: 'Uruguay', position: 'ATA' },
  { name: 'Rodrigo Zalazar', team: 'Uruguay', position: 'MEI' },
  { name: 'Darwin Núñez', team: 'Uruguay', position: 'ATA' },
  { name: 'Facundo Pellistri', team: 'Uruguay', position: 'ATA' },
  { name: 'Brian Rodríguez', team: 'Uruguay', position: 'ATA' },
  { name: 'Rodrigo Aguirre', team: 'Uruguay', position: 'ATA' },
  { name: 'Federico Viñas', team: 'Uruguay', position: 'ATA' },

  // Qatar
  { name: 'Mahmoud Abunada', team: 'Qatar', position: 'GOL' },
  { name: 'Meshaal Barsham', team: 'Qatar', position: 'GOL' },
  { name: 'Salah Zakaria', team: 'Qatar', position: 'GOL' },
  { name: 'Ayoub Al-Alawi', team: 'Qatar', position: 'DEF' },
  { name: 'Boualem Khoukhi', team: 'Qatar', position: 'DEF' },
  { name: 'Homam Al-Amin', team: 'Qatar', position: 'DEF' },
  { name: 'Lucas Mendes', team: 'Qatar', position: 'DEF' },
  { name: 'Issa Laye', team: 'Qatar', position: 'DEF' },
  { name: 'Pedro Miguel', team: 'Qatar', position: 'DEF' },
  { name: 'Al-Hashmi Al-Hussain', team: 'Qatar', position: 'DEF' },
  { name: 'Sultan Al-Brake', team: 'Qatar', position: 'DEF' },
  { name: 'Assim Madibo', team: 'Qatar', position: 'MEI' },
  { name: 'Abdulaziz Hatem', team: 'Qatar', position: 'MEI' },
  { name: 'Ahmed Fathy', team: 'Qatar', position: 'MEI' },
  { name: 'Karim Boudiaf', team: 'Qatar', position: 'MEI' },
  { name: 'Jassem Gaber', team: 'Qatar', position: 'MEI' },
  { name: 'Mohamed Mannaj', team: 'Qatar', position: 'MEI' },
  { name: 'Ahmed Al-Ganehi', team: 'Qatar', position: 'ATA' },
  { name: 'Ahmed Alaa', team: 'Qatar', position: 'ATA' },
  { name: 'Akram Afif', team: 'Qatar', position: 'ATA' },
  { name: 'AlMoez Ali', team: 'Qatar', position: 'ATA' },
  { name: 'Edmilson Junior', team: 'Qatar', position: 'ATA' },
  { name: 'Hasan Al-Haydos', team: 'Qatar', position: 'ATA' },
  { name: 'Mohammed Muntari', team: 'Qatar', position: 'ATA' },
  { name: 'Tahsin Mohammed', team: 'Qatar', position: 'ATA' },
  { name: 'Youssef Abdulrazzaq', team: 'Qatar', position: 'ATA' },

  // Irã
  { name: 'Alireza Beyranvand', team: 'Iran', position: 'GOL' },
  { name: 'Hosein Hoseini', team: 'Iran', position: 'GOL' },
  { name: 'Payam Niazmand', team: 'Iran', position: 'GOL' },
  { name: 'Shoja Khalilzadeh', team: 'Iran', position: 'DEF' },
  { name: 'Hosein Kanaani', team: 'Iran', position: 'DEF' },
  { name: 'Ali Nemati', team: 'Iran', position: 'DEF' },
  { name: 'Daniyal Eiri', team: 'Iran', position: 'DEF' },
  { name: 'Ehsan Hajisafi', team: 'Iran', position: 'DEF' },
  { name: 'Milad Mohammadi', team: 'Iran', position: 'DEF' },
  { name: 'Saleh Hardani', team: 'Iran', position: 'DEF' },
  { name: 'Ramin Rezaeiyan', team: 'Iran', position: 'DEF' },
  { name: 'Saman Ghodoos', team: 'Iran', position: 'MEI' },
  { name: 'Saeid Ezatollahi', team: 'Iran', position: 'MEI' },
  { name: 'Rouzbeh Cheshmi', team: 'Iran', position: 'MEI' },
  { name: 'Amir Mohammad Razagah Niya', team: 'Iran', position: 'MEI' },
  { name: 'Mohammad Ghorbani', team: 'Iran', position: 'MEI' },
  { name: 'Mehdi Ghayedi', team: 'Iran', position: 'MEI' },
  { name: 'Ariya Yousefi', team: 'Iran', position: 'MEI' },
  { name: 'Alireza Jahanbakhsh', team: 'Iran', position: 'MEI' },
  { name: 'Mehdi Torabi', team: 'Iran', position: 'MEI' },
  { name: 'Mohammad Mohebbi', team: 'Iran', position: 'MEI' },
  { name: 'Mehdi Taremi', team: 'Iran', position: 'ATA' },
  { name: 'Amirhossein Hosseinzadeh', team: 'Iran', position: 'ATA' },
  { name: 'Denis Dargahi', team: 'Iran', position: 'ATA' },
  { name: 'Ali Alipour', team: 'Iran', position: 'ATA' },
  { name: 'Shahriyar Moghanloo', team: 'Iran', position: 'ATA' },
]